supaglue-labs/supaglue

- docs/package.json
- yarn.lock
`@docusaurus/plugin-google-gtag` was ahead of other packages
> chore: update docusaurus versions to all be in line

- apps/sample-app/pages/_app.tsx
Setting `h-full` on the inner div makes it overflow when the header is present.
Instead, we should just make the parent a flex box and the inner div take up all remaining room.
> fix(sample-app): fix sidebar height

- packages/nextjs/src/components/Switch/styles.ts
Since if the enabled Switch is gray, it could be mistaken for disabled.
Before:
After:
> fix: change background color of enabled Switch from gray to indigo

- packages/nextjs/src/components/Switch/styles.ts
I accidentally used `slate9` instead of `indigo9` when I refactored the CSS.
> fix: fix switch on color

- packages/nextjs/src/providers/SupaglueProvider.tsx
Without this, the `useSalesforceIntegration` wasn't making a network call and therefore always redirecting away from `/integrations/salesforce` to `/integrations` on load.
> fix: add SWRConfig to SupaglueProvider for useSalesforceIntegration hook

- .yarnrc.build.yml
- apps/api/Dockerfile
- apps/sample-app/Dockerfile
- turbo.json
Don't install `@swc/core` for all architectures as part of the image build process
> fix(api): make docker images smaller

- docs/versioned_docs/version-0.1.x/quickstart.md
We no longer need to click "Configure" since we auto-redirect to the salesforce integrations page.
> docs: update quickstart instructions

- apps/api/integrations/services/integration_service.ts
- apps/api/routes/integration.ts
- apps/api/routes/oauth.ts
- apps/api/syncs/services/sync_service.ts
- packages/nextjs/src/components/Button/styles.ts
- packages/nextjs/src/components/FieldMapping/styles.ts
- packages/nextjs/src/components/IntegrationCard/IntegrationCard.tsx
- packages/nextjs/src/components/IntegrationCard/styles.ts
- packages/nextjs/src/components/SalesforceConnectButton/SalesforceConnectButton.tsx
- packages/nextjs/src/components/SalesforceDisconnectButton/SalesforceDisconnectButton.tsx
- packages/nextjs/src/components/SalesforceDisconnectButton/index.ts
- packages/nextjs/src/components/Select/styles.ts
- packages/nextjs/src/components/index.ts
Adds a button to disconnect a Salesforce account and delete the end user's integration.
TO DO (later):
- Right now, clicking "Disconnect" both logs the user out and deletes the SFDC integration. In the future, we might allow users to keep the integration but disconnect in order to switch the Salesforce account they use to authenticate
- Currently the `DELETE /integrations/:id` endpoint takes a _long_ time and gives no feedback to the user - we should add a button loading state and consider offloading the Temporal schedule deletions to an async task
- ~See if there's an alternative to appending `prompt=login` to the SFDC authz url.~ (Currently, without it, a user gets automatically logged in after clicking "Disconnect" and then "Connect" again. @lucasmarshall do you know why this might be? …
> feat: add SalesforceDisconnectButton component

- apps/api/developer_config/services/developer_config_service.ts
- apps/api/integrations/services/integration_service.ts
- apps/api/prisma/migrations/20230207213130_sync_type/migration.sql
- apps/api/prisma/schema.prisma
- apps/api/syncs/entities/sync.ts
This change involves adding a non-nullable column `type` to `syncs` table. If you already have `syncs`, you may want to truncate your `syncs` table before applying this migration. Alternatively, reset your environment with `docker compose down -v`.
> feat!: inbound sync types

- apps/cli/src/commands/syncs_commands/resume.ts
```console
$ syncs list --customer-id user1 --sync-config-name Opportunities
ℹ Info: Syncs for customer user1
╔═══════════════╤═════════╤══════════════════════════╤══════════════════════════╗
║ Sync Name     │ Enabled │ Last Run                 │ Next Run                 ║
╟───────────────┼─────────┼──────────────────────────┼──────────────────────────╢
║ Contacts      │ Yes     │ 2023-02-08T00:00:10.629Z │ 2023-02-08T00:15:00.000Z ║
╟───────────────┼─────────┼──────────────────────────┼──────────────────────────╢
║ Opportunities │ No      │ n/a                      │ n/a                      ║
╟───────────────┼─────────┼──────────────────────────┼──────────────────────────╢
║ Leads         │ No      │ n/a                      │ n/a                      ║ …
```
> feat(cli): syncs resume command

- apps/sample-app/pages/integrations/[type].tsx
- packages/nextjs/src/components/TriggerSyncButton/TriggerSyncButton.tsx
- packages/nextjs/src/components/TriggerSyncButton/styles.ts
Right now the toast logic is written inside the sample app.
This is step 1 of moving the entire config setting into nextjs package.
We should consider making the toast a primitive, but it's tricky because it depends on its parent container. We should probably have a `NotificationProvider` that manages all of these, but punting for now.
> chore: move toast to TriggerSyncButton component

- apps/api/routes/field.ts
- packages/nextjs/src/components/FieldMapping/FieldMapping.tsx
- packages/nextjs/src/primitives/Select/Select.tsx
When using field names, custom fields are displayed with a `__c` suffix, e.g. `FavoriteFruit__c`.
> fix: use field labels, rather than names, in FieldMapping dropdowns

- apps/sample-app/supaglue-config/inbound/contact.ts
- apps/sample-app/supaglue-config/inbound/lead.ts
- apps/sample-app/supaglue-config/inbound/opportunity.ts
- apps/sample-app/supaglue-config/outbound/contact.ts
- apps/sample-app/supaglue-config/postgres_credentials.ts
- apps/sample-app/supaglue-config/salesforce_credentials.ts
- packages/sdk/src/customer/base/salesforce.ts
- packages/sdk/src/customer/common/index.ts
- packages/sdk/src/customer/common/salesforce.ts
- packages/sdk/src/customer/index.ts
- packages/sdk/src/developer_config.ts
- packages/sdk/src/internal/base/postgres.ts
- packages/sdk/src/internal/common/index.ts
- packages/sdk/src/internal/common/postgres.ts
- packages/sdk/src/internal/index.ts
As per conversation with @tomkit offline, cleaning up the common types namespacing a bit.
The namespacing/scoping is becoming kind of long, but we can revisit that later.
> chore: clean up common types for SDK

- apps/api/developer_config/entities/developer_config.ts
Just a comment in code to explain difference between developer specifying an SF object vs expecting customer to choose one.
> docs: salesforce object config comment

- apps/api/routes/field.ts
- apps/api/routes/sync.ts
- apps/api/syncs/entities/sync.ts
- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
- packages/nextjs/src/elements/FieldMapping/styles.ts
- packages/nextjs/src/lib/types.ts
- packages/nextjs/src/primitives/icons/index.ts
- packages/nextjs/src/primitives/icons/xIcon.tsx
Depends on #104
Adds a simple button to allow customers to create custom properties for the purposes of their SFDC integration. Note that these are application-side custom properties, not Salesforce custom fields.
For now, this is a fairly naive implementation that assumes that customer-defined properties aren't consumed by the application outside of the Salesforce syncs.
**Caveats**
1. Custom properties cannot be renamed
2. Custom properties cannot be reused across syncs, even for the same sObjects (same as field mappings). We're planning to refactor how syncs are modeled to enable field mappings, custom properties, etc. to be shared across syncs.
TO DO (follow-up):
> feat: enable customers to create custom properties in the sync config

- apps/api/developer_config/entities/developer_config.ts
- apps/api/prisma/schema.prisma
- apps/sample-app/prisma/migrations/20230209203536_add_extra_attrbiutes_column_to_salesforce_contacts/migration.sql
- apps/sample-app/prisma/schema.prisma
- apps/sample-app/supaglue-config/inbound/contact.ts
- packages/sdk/src/internal/base/postgres.ts
Add a new config property to indicate where customer-defined properties should be written to in a Postgres destination. For now, this must be a `jsonb` column on the same table that we're writing Salesforce objects to.
Includes a migration to add a custom properties column to the `salesforce_contacts` table in the sample app.
> chore: add customPropertiesColumn to Postgres destination config

- apps/api/temporal/sdk/internal_integrations/postgres.ts
- apps/sample-app/pages/index.tsx
- apps/sample-app/prisma/schema.prisma
Write to custom properties when syncing objects from Salesforce to Postgres.
Does not include:
> feat: Support custom properties in inbound syncs to Postgres

- packages/nextjs/src/elements/TriggerSyncButton/styles.ts
> fix: vertically align toast with TriggerSyncButton

- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
- packages/nextjs/src/lib/types.ts
Custom properties are only enabled for inbound contacts syncs right now, so hide the button for all other syncs.
> fix: only show the '+ Add custom property' button if postgres schema supports it

- apps/api/prisma/migrations/20230214002909_field_mapping/migration.sql
- apps/api/prisma/migrations/20230214010611_entity_integration_config/migration.sql
- apps/api/prisma/schema.prisma
To support the new concept of `Entity`, we want to store `EntityIntegrationConfig` as a standalone object in the DB. This would consist of both `fieldMapping` and `customProperties`.
> feat: create entity_integration_configs db table migration

- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
1. Fixes a bug where removing a custom field doesn't actually remove it from the field mapping due to a typo (good catch @asdfryan)
2. Removes the X icon to delete a new custom property before it's been created. Because we save the new custom property on blur, we end up creating the new property even if the user actually clicked on the X.
> fix: fix custom fields bugs (2 out of 3)

- packages/nextjs/src/primitives/icons/styles.ts
- packages/nextjs/src/primitives/icons/xIcon.tsx
The real problem was that JSX was not properly interpreting the css. I also refactored the component styles to take into account theming (which is currently not necessary right now, but is convenient if in the future we choose to do so)
> fix(nextjs): fix xicon styling

- apps/sample-app/components/PageTabs.tsx
- apps/sample-app/hooks.ts
- apps/sample-app/pages/index.tsx
- apps/sample-app/pages/integrations/[type].tsx
* Fix url hash to be tab name and not an object
* Remove `App` prefix which is redundant (it's already in the `App Objects` page
* Share `pageTabs` array across 2 different pages so they don't diverge
* Rename variables to make code more readable
> fix: sample app tabs

- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
- packages/nextjs/src/elements/FieldMapping/styles.ts
No functional change, this just updates the custom property UX such that we show a (disabled) salesforce field dropdown alongside the text input where you can add the name of your new custom property.
In order to allow selecting a salesforce field before naming a custom property, we'll need to refactor the FieldMapping component and allow custom properties to be updated as well as created and deleted. This raises some product questions about how we should model custom properties, whether they need IDs, etc., and whether supaglue config is the correct place for that metadata or whether it should actually live in the developer's application.
> feat: update custom property UX

- apps/api/temporal/sdk/internal_integrations/postgres.ts
- apps/sample-app/supaglue-config/inbound/contact.ts
- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
- packages/types/src/sync_config.ts
Adds a separate config property to the `SyncConfig` that governs whether or not a customer is able to add custom fields to a field mapping. Note that for postgres integrations, a `customPropertiesColumn` is also required.
Also fixes an issue where `destination.schema.fields` is out of sync with the `defaultFieldMapping`, so that fields specified in the latter but not the former do not appear in the customer's field mapping.
> feat: add customPropertiesEnabled setting to sync configs

- packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
- packages/nextjs/src/elements/FieldMapping/styles.ts
Refactors the `FieldMapping` component in order to improve UX for adding and removing custom properties:
- Allow selecting a Salesforce field before naming the custom property
- Prevent glitchy-seeming UI when creating a new custom property (where the text input stays in the DOM even after the field mapping has been re-rendered with the new field)
> feat: improve custom properties UX

- apps/api/temporal/sdk/customer_integrations/salesforce.ts
- apps/api/temporal/sdk/internal_integrations/postgres.ts
- apps/cli/src/commands/syncs_commands/resume.ts
- apps/sample-app/supaglue-config/outbound/contact.ts
Enables custom properties to be synced from Postgres > Salesforce.
Also:
- For now, adds a hardcoded `pollingTimeout` of 10 seconds when waiting for the results of a bulk upload (in the future, this should be in a config file).
- Logs the result of a bulk upload job, including any records that errored
- Updates the sample app's outbound contact syncs to enable custom properties
> feat: support custom properties in outbound syncs from Postgres

- apps/api/lib/posthog.ts
This is so we can aggregate events by route, like `/crm/v1/opportunities/:opportunity_id` and `/oauth/connect`.
> fix: add route to properties on posthog api events

- packages/core/dependency_container.ts
- packages/core/package.json
- packages/core/remotes/crm/salesforce/index.ts
- packages/core/services/account_service.ts
- packages/core/services/common_model_base_service.ts
- packages/core/services/contact_service.ts
- packages/core/services/lead_service.ts
- packages/core/services/opportunity_service.ts
- packages/db/prisma/migrations/20230307235714_camelcase/migration.sql
- packages/db/prisma/schema.prisma
- yarn.lock
there is still a lot more to do here. for example:
- we manually list out columns right now. maybe we can get them from prisma somehow, or we should ditch prisma for common model
- we should stream data into COPY from SF instead of doing things serially (pipelining)
- on initial load, we can avoid doing the temp table COPY and just write directly to the common model table
- don't manually write `api` schema. rely on config instead
> feat: really janky version of COPY to postgres for syncs

- docs/docusaurus.config.js
While this adds the docs at `/api/mgmt`, it doesn't provide a link to it yet. We can address that in another PR.
> docs: add mgmt api reference

- .yarnrc.yml
- packages/core/package.json
- packages/core/remotes/crm/hubspot/index.ts
- packages/db/package.json
- packages/sync-workflows/activities/do_sync.ts
- packages/sync-workflows/workflows/run_syncs.ts
- yarn.lock
We can get back to a more modern version of hubspot-api-nodejs when https://github.com/HubSpot/hubspot-api-nodejs/issues/341 is fixed.
> fix: downgrade hubspot client to fix token refresh and add temporal heartbeating

- packages/core/services/common_models/contact_service.ts
- packages/core/services/common_models/lead_service.ts
- packages/core/services/common_models/opportunity_service.ts
- packages/db/index.ts
- packages/sync-workflows/activities/populate_associations.ts
got rid of the prisma calls for populating associations, paging in records, etc. in favor of a simple single query. runs much much faster and avoids connection pool timeouts, lock contention, etc.
> chore: optimize populateAssociations

- .yarnrc.build.yml
need to hoist. otherwise running into temporal issue.
we already hoist in dev but i didn't know to update it also in `.yarnrc.build.yml`
```
supaglue-sync-worker-1  | /packages/sync-workflows/node_modules/@temporalio/activity/lib/index.js:153
supaglue-sync-worker-1  |             throw new Error('Activity context not initialized');
supaglue-sync-worker-1  |             ^
supaglue-sync-worker-1  |
supaglue-sync-worker-1  | Error: Activity context not initialized
supaglue-sync-worker-1  |     at Context.current (/packages/sync-workflows/node_modules/@temporalio/activity/lib/index.js:153:19)
```
> fix: hoist packages in .yarnrc.build.yml

- openapi/crm/components/schemas/objects/account.yaml
- openapi/crm/components/schemas/objects/addresses.yaml
- openapi/crm/components/schemas/objects/email_addresses.yaml
- openapi/crm/components/schemas/objects/phone_numbers.yaml
- openapi/crm/openapi.bundle.json
- openapi/crm/paths/accounts.yaml
- openapi/crm/paths/accounts@_search.yaml
- openapi/crm/paths/accounts@{account_id}.yaml
- openapi/crm/paths/contacts.yaml
- openapi/crm/paths/contacts@_search.yaml
- openapi/crm/paths/leads.yaml
- packages/core/remotes/crm/hubspot/index.ts
- packages/core/remotes/crm/hubspot/mappers.ts
- packages/core/remotes/crm/salesforce/index.ts
- packages/core/remotes/crm/salesforce/mappers.ts
- packages/core/types/base.ts
- packages/schemas/gen/crm.ts
supported email types: `primary`, `work`
supported phone types: `primary`, `mobile`, `fax`
supported address types:
- salesforce accounts: `billing` , `shipping`
- salesforce contacts: `mailing`, `other`
- salesforce leads: `primary`
- hubspot accounts: `primary`
- hubspot contacts: `primary`
Next PR will implement POST/PATCH for these fields
> fix: strictly type email addresses, addresses, and phone number types

- apps/api/routes/internal/v1/customer/index.ts
- packages/core/mappers/customer.ts
- packages/core/services/customer_service.ts
- packages/core/types/customer.ts
- Revert to the non-joined Customer type for public API
- Use a safe joined-relation for internal API
SUP1-140
> fix: don't send up connection credentials

- docker-compose.yml
- packages/core/lib/distinct_identifier.ts
- use `SUPAGLUE_DEPLOYMENT_ID` if a developer opts in, suffix it to avoid collisions
SUP1-62
> chore: developer opted-in deployment id

- apps/api/middleware/openapi.ts
just so we don't accidentally send any extra fields anywhere
> chore: remove additional fields for openapi

- apps/api/routes/internal/v1/auth/index.ts
- apps/mgmt-ui/src/pages/api/auth/[...nextauth].ts
- packages/core/mappers/sg_user.ts
- packages/core/services/sg_user_service.ts
- packages/core/types/sg_user.ts
- packages/db/prisma/migrations/20230320180203_application_sg_user_relation/migration.sql
- packages/db/prisma/schema.prisma
- packages/db/prisma/seed.ts
For non-Cloud, any `SgUser` can access any `Application` and there are no roles. This gets rid of the relationship (to avoid dealing with roles, M-M mapping between SGUser and Application, etc.)
> chore: remove relationship between SgUser and Application

- apps/api/routes/mgmt/v1/index.ts
- apps/api/routes/oauth.ts
- apps/api/services/connection_writer_service.ts
- openapi/mgmt/components/schemas/objects/connection.yaml
- openapi/mgmt/openapi.bundle.json
- openapi/mgmt/paths/connections.yaml
- openapi/mgmt/paths/connections@{connection_id}.yaml
- packages/core/mappers/connection.ts
- packages/core/remotes/crm/hubspot/index.ts
- packages/core/services/connection_service.ts
- packages/core/types/connection.ts
- packages/db/prisma/migrations/20230327202406_connection_remote_account_id/migration.sql
- packages/db/prisma/migrations/20230328175058_connection_remote_id/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/gen/mgmt.ts
All `connection` objects now have a `remote_account_id` representing the account Id in the remote provider (see screenshot below)
Please reset all your connections, or hit the `{{baseUrl}}/mgmt/v1/_backfill_remote_account_ids` endpoint to backfill the `remote_account_id`s
> feat: remote_account_id on connection

- packages/core/package.json
- packages/core/remotes/crm/base.ts
- packages/core/remotes/crm/hubspot/index.ts
- packages/core/services/common_models/account_service.ts
- packages/core/services/common_models/contact_service.ts
- packages/core/services/common_models/lead_service.ts
- packages/core/services/common_models/opportunity_service.ts
- packages/core/types/sync.ts
- packages/sync-workflows/activities/import_records.ts
- packages/sync-workflows/workflows/run_syncs.ts
- yarn.lock
https://github.com/supaglue-labs/supaglue/issues/306
1. For all common models in hubspot, this first calls the search endpoint to get new records.
2. For deals and contacts in hubspot, this also calls the association endpoint to get all associated companies for those two object types.
> feat: [Part 2] incremental syncs in hubspot

- packages/core/remotes/crm/hubspot/index.ts
- packages/core/services/common_models/account_service.ts
- packages/core/services/common_models/base_service.ts
- packages/core/services/common_models/contact_service.ts
- packages/core/services/common_models/lead_service.ts
- packages/core/services/common_models/opportunity_service.ts
- packages/core/services/common_models/user_service.ts
- packages/core/types/crm/account.ts
- packages/core/types/crm/contact.ts
- packages/core/types/crm/lead.ts
- packages/core/types/crm/opportunity.ts
- packages/core/types/crm/user.ts
- packages/core/types/sync.ts
- packages/sync-workflows/activities/import_records.ts
- packages/sync-workflows/workflows/run_syncs.ts
https://github.com/supaglue-labs/supaglue/issues/489
this actually pulls in deleted objects from hubspot. we cannot use search api, since it doesn't allow filtering on archived. so we have to pull in all the deleted objects all the time (we're hoping that people don't archive that many objects usually). down the road, we might consider using webhook instead
> feat: pull in deleted objects from hubspot

- apps/api/services/sync_service.ts
- packages/sync-workflows/workflows/index.ts
- packages/sync-workflows/workflows/run_sync.ts
Fixes: #### 
Renaming `RunSyncs` workflow to `RunSync` now that we have a `Sync` object to avoid confusion. A `Sync` coordinates all the individual record imports for account, contact, opportunity, etc.
> BREAKING CHANGE: rename RunSyncs to RunSync now that we have a Sync object

- package.json
- packages/sdk/mgmt/java/pom.xml
- yarn.lock
Corrects all current dependabot alerts in the repo.
Tested locally. The `got` upgrade was particularly risky since it's a couple of major versions behind. The only think that depended on it was `docusaurus` and docs still work fine
> fix: Dependabot alerts

- openapi/mgmt/components/schemas/webhook-payload.yaml
- openapi/mgmt/openapi.bundle.json
- packages/schemas/gen/mgmt.ts
- packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts
- packages/types/webhook.ts
Fixes: https://github.com/supaglue-labs/supaglue/issues/557
Add provider name to payload so webhook can be entirely data driven (we can remove provider from env var in typescript-syncer)
Looked at doc slocally
> chore: add provider name to webhook payload

- packages/core/services/common_models/account_service.ts
- packages/core/services/common_models/base_service.ts
- packages/core/services/common_models/contact_service.ts
- packages/core/services/common_models/event_service.ts
- packages/core/services/common_models/lead_service.ts
- packages/core/services/common_models/opportunity_service.ts
- packages/db/prisma/migrations/20230405163512_indexes/migration.sql
- packages/db/prisma/schema.prisma
- packages/sync-workflows/activities/populate_associations.ts
- packages/sync-workflows/workflows/run_sync.ts
Fixes: https://github.com/supaglue-labs/supaglue/issues/422
These are some indexes / query tweaks that in theory may help with:
1. upserting from temp table to main table
1. populating associations
1. list queries against our API sorted by `last_modified_date`
Need to generate migration, test these out, etc., consider other indexes, partitions, etc.
> chore: db indexes for performance

- packages/core/services/common_models/base_service.ts
Make index idempotent (same as creating the temp table) in `upsertRemoteCommonModels`
> fix: idempotent index for temp teable

- apps/api/routes/internal/v1/index.ts
- apps/api/routes/mgmt/v1/index.ts
- apps/api/services/connection_and_sync_service.ts
The previous PR would delete orphaned WFs/schedules in Temporal.
This PR improves the endpoint to also spin up new Temporal schedules if somehow it was manually deleted by someone (even though the sync exists in Postgres).
Also moved endpoint to /internal
> chore: manual endpoint for fixing temporal syncs

- apps/api/routes/oauth.ts
- packages/core/remotes/crm/salesforce/index.ts
- packages/types/connection.ts
- scripts/build_and_push.sh
This fixes a few issues:
- the main issue: persist connection loginUrl so we can use the correct url when refreshing access tokens
- don't infinitely retry when refreshing a token fails
- introduce a timeout when fetching (this is unrelated, but good to do anyway)
> fix: salesforce refresh

- apps/api/routes/internal/v1/index.ts
- packages/core/services/common_models/account_service.ts
- packages/core/services/common_models/base_service.ts
- packages/core/services/common_models/contact_service.ts
- packages/core/services/common_models/event_service.ts
- packages/core/services/common_models/lead_service.ts
- packages/core/services/common_models/opportunity_service.ts
- packages/core/services/common_models/user_service.ts
This fixes writing `last_modified_at` upon create and update calls. In addition, it provides a backfill endpoint so that after the fix is deployed, we can backfill `last_modified_at` in the DB so that in a subsequent release, we can apply a migration to make `last_modified_at` non-NULL.
> fix: write last_modified_at on create and update calls

- packages/sync-workflows/workflows/run_sync.ts
This is a temporary "fix" to not advance watermarks after importRecords, so that if importRecords succeeds and populateAssociations fails, we will still populate all associations.
> fix: make sure to run populateAssociations for previous records even if watermark moved

- packages/core/lib/logger.ts
- packages/core/package.json
- yarn.lock
This PR makes it so that we intercept Warnings with error payloads and send them as errors to Sentry.
This works as a workaround because:
- Temporal logs uncaught errors as warnings (with stack trace etc)
- By the time the sync has failed, the activity failure object does not have the stack trace in its original form
> fix: sentry stack trace

- apps/mgmt-ui/src/components/configuration/IntegrationDetailsPanel.tsx
- openapi/mgmt/components/schemas/objects/integration_config.yaml
- openapi/mgmt/openapi.bundle.json
- Don't allow sync period ms below 1 minute
Separately, when adding validation, I noticed sometimes the sync period shown changed non-deterministically
- Update react hook to always set values when integration is fetched
- Fix `mutate` to not have potentially contain duplicated entry for the case of updates
- Use `optimisticData` for revalidation so value is the latest one saved
Fixes: #### 
> fix: validate sync period ms. fix swr refetch

- packages/sync-workflows/workflows/run_sync.ts
This is because `populateAssociations` happens in 1 step per model, so if there are many records, it may time out.
> chore: increase heartbeat timeout for populate associations

- apps/mgmt-ui/src/components/configuration/integration/IntegrationDetailsPanel.tsx
- openapi/mgmt/components/schemas/objects/integration_config.yaml
- openapi/mgmt/openapi.bundle.json
Merge from `main`
- Don't allow sync period ms below 1 minute
Separately, when adding validation, I noticed sometimes the sync period shown changed non-deterministically
- Update react hook to always set values when integration is fetched
- Fix `mutate` to not have potentially contain duplicated entry for the case of updates
- Use `optimisticData` for revalidation so value is the latest one saved
Fixes: #### 
> fix: validate sync period ms. fix swr refetch (#684)

- openapi/crm/openapi.bundle.json
- openapi/mgmt/openapi.bundle.json
Someone missed these in a pr.
They were generated via:
```
yarn generate
```
> chore: add missed generated openapi bundles

- packages/core/remotes/crm/hubspot/index.ts
- packages/core/remotes/crm/hubspot/mappers.ts
Fixes: #743
Changes:
- We will return the name of the pipeline and stage in the `pipeline` and `stage` fields for Hubspot instead of their ids (i.e. `Sales Pipeline` instead of `default`)
- For Create/Update, we accept either the ID or the name (we will do the lookup)
Tested locally -- see screenshots below:
> feat: hubspot stage and pipeline names

- apps/api/routes/oauth.ts
- apps/mgmt-ui/src/hooks/useNextLambdaEnv.ts
- apps/mgmt-ui/src/pages/api/index.ts
- apps/mgmt-ui/src/pages/api/internal/env.ts
- apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
- docs/docs/guides/embedded-links.mdx
- quick-fix: add a button to generate a partial embed link
- make `returnUrl` required in embed link
Example: `https://api.supaglue.io/oauth/connect?applicationId=a4398523-03a2-42dd-9681-c91e3e2efaf4&customerId=external-customer-hubspot&providerName={{providerName}}&returnUrl={{returnUrl}}`
> chore: for devxp, add a quick way to generate a partial embed link

- apps/api/routes/mgmt/v1/force_sync.ts
- apps/api/routes/mgmt/v1/index.ts
- apps/api/services/connection_and_sync_service.ts
- apps/sync-worker/services/sync_service.ts
- openapi/crm/openapi.bundle.json
- openapi/crm/openapi.yaml
- openapi/mgmt/components/schemas/force_sync.yaml
- openapi/mgmt/openapi.bundle.json
- openapi/mgmt/openapi.yaml
- openapi/mgmt/paths/force_sync.yaml
- packages/db/prisma/migrations/20230503003026_sync_resync/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/gen/mgmt.ts
- packages/schemas/mgmt.ts
- packages/sync-workflows/activities/index.ts
- packages/sync-workflows/activities/set_force_sync_flag.ts
- packages/sync-workflows/workflows/run_sync.ts
- packages/types/sync.ts
- POST to `/mgmt/v1/force-sync?customer_id={}&provide_name={}` to schedule a forced full refresh upon the next sync cycle
- adds openapi spec and endpoints
- migration to add a `resync` flag that is consumable by sync-workers upon the start of the forced sync. consumes the flag upon start: if there's a failure, the user has to reschedule
- adds a lightweight class to help with sync state transitions
- tested a forced full sync locally against a sync that moved onto the incremental phase of the "full then incremental" strategy and observed that deleted leads re-appeared after the forced sync
> feat: add force sync feature and endpoint

- apps/api/services/connection_and_sync_service.ts
- apps/sync-worker/services/sync_service.ts
- packages/core/services/connection_service.ts
previously we would only update the period. we want to allow `manuallyUpdateTemporalSyncs` to update the args too in case there are new ones
> chore: allow update of temporal schedule args

- packages/core/remotes/engagement/outreach/index.ts
This is needed in case the outreach sync period is long.
> chore: lazily refresh token for outreach passthrough requests

- apps/api/routes/mgmt/v1/customer/connection/index.ts
- openapi/mgmt/openapi.bundle.json
- openapi/mgmt/paths/connections.yaml
- packages/schemas/gen/mgmt.ts
We already have this in `internal`, but we need to expose this in `mgmt` for use in Cloud temporarily for migrators from self-hosted to Cloud.
> feat: create connection by passing in creds manually

- apps/api/index.ts
I suspect that the 504s are for long running requests. Since we set the keepalive timeout on the ELBs to 4 seconds to keep under the node default of 5 seconds, its probable that the ELB is now timing out the request if it takes longer than the 4 seconds.
After this is deployed, I will bump the ELB idle timeout back up to the default 60 sec.
> fix: bump keepalive timeout to 61 seconds

- docs/docusaurus.config.js
`scripts/prepare_release.sh` doesn't work for 0.9.0 because we changed the way we structure our OpenAPI spec directories
> fix: 0.9.0 docusaurus openapi docs

- apps/api/routes/internal/v1/sync_history.ts
- apps/api/routes/internal/v2/sync_history.ts
- apps/mgmt-ui/src/components/logs/LogsTable.tsx
- apps/mgmt-ui/src/hooks/useSWRWithApplication.ts
- apps/mgmt-ui/src/hooks/useSyncHistory.ts
- apps/mgmt-ui/src/pages/api/internal/sync-history/index.ts
- apps/mgmt-ui/src/pages/applications/[applicationId]/sync_logs/index.tsx
- openapi/common/components/schemas/pagination.yaml
- openapi/v1/crm/openapi.bundle.json
- openapi/v1/engagement/openapi.bundle.json
- openapi/v1/mgmt/openapi.bundle.json
- openapi/v2/crm/openapi.bundle.json
- openapi/v2/engagement/openapi.bundle.json
- openapi/v2/mgmt/openapi.bundle.json
- packages/core/lib/pagination.ts
- packages/core/services/sync_history_service.ts
- packages/schemas/gen/v1/crm.ts
- packages/schemas/gen/v1/engagement.ts
- packages/schemas/gen/v1/mgmt.ts
- packages/schemas/gen/v2/crm.ts
- packages/schemas/gen/v2/engagement.ts
- packages/schemas/gen/v2/mgmt.ts
- packages/types/common.ts
- server-side pagination for sync history mgmt ui page with 100 records at a time
- make the datagrid compact
- disallow client-side  sorting/filtering which will cause trouble when mixed with server pagination
https://github.com/supaglue-labs/supaglue/assets/471516/63f75af7-d9a2-457e-823f-e40664bea334
> feat(mgmt): add pagination to sync history

- docker-compose.override.dev.yml
- docker-compose.yml
temporalite is being deprecated
ideally, we should just `brew install temporal` and use that, but that makes it harder to start up, since we can't just run `docker compose up` and need to run another script too.
Thoughts?
> chore: use new temporal instead of temporalite

- apps/mgmt-ui/src/components/logs/LogsTable.tsx
- openapi/v1/mgmt/components/schemas/sync_history.yaml
- openapi/v1/mgmt/openapi.bundle.json
- openapi/v2/mgmt/components/schemas/sync_history.yaml
- openapi/v2/mgmt/openapi.bundle.json
- packages/core/mappers/sync_history.ts
- packages/core/services/sync_history_service.ts
- packages/db/prisma/migrations/20230606204005_sync_history_num_records_synced/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/gen/v1/mgmt.ts
- packages/schemas/gen/v2/mgmt.ts
- packages/sync-workflows/activities/log_sync_finish.ts
- packages/sync-workflows/workflows/run_managed_sync.ts
- packages/sync-workflows/workflows/run_sync.ts
- packages/types/sync_history.ts
- `num_records_synced` for each sync, `null` is for start of sync and remains such if it fails, otherwise the number of records is used (same value used for the webhook payload)
> chore(mgmt-ui): add number of synced records to sync log page

- docker-compose.override.dev.yml
- docker-compose.yml
Ran into this issue while going through quickstart. In dev override, we use `node:18` image and have no issues with apk, curl, etc. However, for normal quickstart, we use the built `api` image, which apparently doesn't have these tools for us to download temporal and apply search attributes.
```
supaglue2-init-1  |     └─ migration.sql
supaglue2-init-1  |       
supaglue2-init-1  | All migrations have been successfully applied.
supaglue2-init-1  | npm notice 
supaglue2-init-1  | npm notice New minor version of npm available! 9.5.1 -> 9.7.1
supaglue2-init-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
supaglue2-init-1  | npm notice Run `npm install -g npm@9.7.1` to update!
supaglue2-init-1  | npm notice 
supaglue2-init-1  | sh: 3: apk: not found …
```
> chore: reverting back to temporalite

- apps/api/routes/oauth.ts
- apps/api/services/connection_and_sync_service.ts
- openapi/v1/mgmt/components/schemas/objects/connection.yaml
- openapi/v1/mgmt/openapi.bundle.json
- packages/core/mappers/connection.ts
- packages/db/prisma/migrations/20230613033542_remove_remote_id/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/gen/v1/mgmt.ts
- packages/types/connection.ts
I was touching oauth code earlier today. Verified remote_id isn't being used so removing.
> chore(cleanup): remove unused remote_id superseded by instance_url

- apps/mgmt-ui/src/components/AccountMenu/index.tsx
- apps/mgmt-ui/src/hooks/useNextLambdaEnv.ts
- apps/mgmt-ui/src/layout/Navigator.tsx
- apps/mgmt-ui/src/pages/api/internal/env.ts
- use clerk hosted pages for profile and team mgmt on cloud
https://github.com/supaglue-labs/supaglue/assets/471516/37467397-bd82-4800-a8a7-b326c96c07b8
> feat(mgmt-ui): add profile and team mgmt for cloud

- README.md
- docs/docs/quickstart.mdx
When following the quickstart documentation, you're instructed to go to the management UI after `docker-compose up`, but the default admin credentials aren't listed anywhere that I could see. This adds knowledge of the defaults, as well as information on how to modify the defaults if you wish.
> docs: add default admin credentials to quickstart docs

- packages/core/destination_writers/postgres.ts
Avoid using `LIKE ${tableName}` because destination tables may have additional constraints + generated columns
> fix: explicit creation of temp tables

- packages/core/lib/webhook.ts
- packages/core/mappers/application.ts
- packages/db/prisma/migrations/20230621214425_application_environment/migration.sql
- packages/db/prisma/schema.prisma
- packages/sync-workflows/activities/log_sync_finish.ts
- packages/types/application.ts
- add `environment` field to application
- lower webhook from error to warn
- warn on sync failures for `environment` === `development` (i'll set this for certain customer applications)
> chore: oncall alert cleanup

- apps/api/routes/internal/index.ts
- apps/mgmt-ui/src/client.ts
- apps/mgmt-ui/src/components/configuration/provider/DeleteProviderButton.tsx
- apps/mgmt-ui/src/components/configuration/provider/ProviderDetailsPanel.tsx
- apps/mgmt-ui/src/components/configuration/syncConfig/DeleteSyncConfig.tsx
- apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx
- apps/mgmt-ui/src/pages/api/internal/providers/[...providerId].ts
- apps/mgmt-ui/src/pages/api/internal/sync-configs/[...syncConfigId].ts
- packages/core/services/provider_service.ts
- packages/core/services/sync_config_service.ts
caveat: sometimes deleting providers and sync configs will fail (because there are existing connections). Because of how our nextjs proxy / client is written, we don't propagate this information to the FE so we don't know when the BE request fails. We need to fix this.
> feat(mgmt-ui): Enable deleting providers and sync configs

- apps/api/routes/internal/sync_config/index.ts
- apps/api/routes/mgmt/v2/customer/connection/index.ts
- apps/api/routes/mgmt/v2/customer/connection/sync/index.ts
- apps/api/routes/mgmt/v2/sync_config/index.ts
- apps/api/services/connection_and_sync_service.ts
- apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
- openapi/v2/mgmt/components/schemas/objects/schema_mappings_config.yaml
- openapi/v2/mgmt/components/schemas/objects/sync.yaml
- openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
- openapi/v2/mgmt/openapi.bundle.json
- openapi/v2/mgmt/openapi.yaml
- openapi/v2/mgmt/paths/connections@{connection_id}@sync.yaml
- packages/core/lib/schema.ts
- packages/core/remotes/crm/base.ts
- packages/core/remotes/crm/hubspot/index.ts
- packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
- packages/core/remotes/crm/salesforce/index.ts
- packages/core/services/sync_config_service.ts
- packages/db/prisma/migrations/20230621225824_schema_mappings_config/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/gen/v2/mgmt.ts
- packages/schemas/v2/mgmt.ts
- packages/sync-workflows/activities/index.ts
- packages/sync-workflows/activities/sync_raw_records_to_destination.ts
- packages/sync-workflows/services/sync_service.ts
- packages/types/field_mapping_config.ts
- packages/types/sync.ts
- packages/types/sync_config.ts
- Developer can define schema
- Customer can choose how to map to schema
- Developer can enable/disable sync (distinct from pause/unpause... that isn't implemented yet)
Example config for `SyncConfig`:
```
{
"application_id": "f72c1b96-38fc-42ca-a82a-68e81f3cbebc",
"provider_id": "c92b0374-7c4f-42fe-9506-65c7e297dcbc",
"destination_id": "59ab3dc1-a51a-4bb8-bf36-99c0c4757713",
"config": {
"common_objects": [],
"default_config": {
"period_ms": 3600000,
"strategy": "full then incremental"
},
"standard_objects": [
{
"object": "company",
"schema": {
"type": "defined",
"fields": [
{
"name": "new_name",
"mapped_name": "name"
},
{
"name": "new_city",
"mapped_name": "city"
},
{
"name": "best_time"
}
],
"allow_additional_field_mappings": true
}
}
],
"custom_objects": [
{
"object": "trucks"
}
]
}
} …
```
> chore: add field mapping for syncs

- packages/db/prisma/migrations/20230622192846_required_sync_config_id/migration.sql
- packages/db/prisma/schema.prisma
- packages/sync-workflows/services/sync_service.ts
- packages/types/sync.ts
Confirmed this is safe to push in prod and staging:
```
supaglue=> select * from syncs where sync_config_id is null;
(0 rows)
```
> chore: make sync_config_id required

- packages/db/package.json
- yarn.lock
Upgrading didn't fix the connection issues, so try downgrading to the version we used before the 0.11.0 release.
> chore: downgrade prisma

- apps/api/routes/mgmt/v2/webhook/index.ts
- apps/mgmt-ui/src/components/ApplicationMenu/index.tsx
- apps/mgmt-ui/src/components/configuration/ApiKeyTabPanel.tsx
- apps/mgmt-ui/src/components/configuration/DeleteWebhook.tsx
- apps/mgmt-ui/src/components/configuration/RegenerateApiKey.tsx
- apps/mgmt-ui/src/components/configuration/provider/DeleteProviderButton.tsx
- apps/mgmt-ui/src/components/configuration/syncConfig/DeleteSyncConfig.tsx
- apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx
- apps/mgmt-ui/src/components/connections/DeleteConnection.tsx
- apps/mgmt-ui/src/components/customers/DeleteCustomer.tsx
- apps/mgmt-ui/src/components/customers/NewCustomer.tsx
- apps/mgmt-ui/src/components/modals/ConfirmationModal.tsx
- apps/mgmt-ui/src/components/modals/DeleteConfirmationModal.tsx
- apps/mgmt-ui/src/components/modals/DeleteResourceConfirmationModal.tsx
- apps/mgmt-ui/src/components/modals/index.ts
- apps/mgmt-ui/src/pages/applications/[applicationId]/customers/[customerId]/connections/index.tsx
- apps/mgmt-ui/src/pages/applications/[applicationId]/customers/index.tsx
Fixes SUP1-428
Refactor modal code to re-use same component. This also includes some other misc cleanups.
Also swaps cancel + confirm buttons.
Tested locally
> chore: refactor modals

- apps/mgmt-ui/src/components/configuration/schema/SchemaDetailsPanel.tsx
Previously you had to click on the very small chevron icon to expand. Now you can click on the whole row to expand.
Tested locally
https://www.loom.com/share/2fb7f2e5321644ad97f0de6ff8ff1be1
> chore: make Advanced Field Settings clickable

- packages/sync-workflows/activities/do_process_sync_changes.ts
- packages/sync-workflows/workflows/process_sync_changes.ts
race condition causing flag to be ignored
> fix: only reset full flag for processSyncChanges for manually-triggered run

- apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
- packages/core/remotes/impl/gong/index.ts
- packages/core/remotes/impl/gong/mappers.ts
- packages/core/services/connection_service.ts
- packages/core/services/sync_config_service.ts
Supports syncing standard objects for Gong.
Caveats:
- even if a field mapping is set, it's ignored
- haven't tested real rate limiting (429), because I didn't run into it while testing; we can artificially try to hit 429 if we want
> feat: sync standard objects for gong

- apps/salesforce-pub-sub/index.ts
- packages/core/remotes/base.ts
- packages/core/remotes/impl/gong/index.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
- packages/core/remotes/impl/outreach/index.ts
- packages/core/remotes/impl/pipedrive/index.ts
- packages/core/remotes/impl/salesforce/index.ts
- packages/core/services/connection_service.ts
- packages/core/services/remote_service.ts
we need to be persisting new refresh tokens.
for gong, this is critical, since the previous refresh token is invalidated when you refresh the access token
> fix: persist new refresh token

- apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
- show correct common object selections for provider category
- don't autofill by default
> fix: common object syncconfig

- apps/mgmt-ui/src/utils/companyToIcon.tsx
> fix: missing mongodb icon on mongodb config page

- packages/core/remotes/impl/apollo/index.ts
Fixes: SUP1-465
It seems the Apollo API uses the body for the api token for POST/PUT/PATCH while using the query parameters for GET requests, so we need to override the `sendPassthroughRequest` to properly do this.
Tested locally
> feat: support apollo passthrough

- packages/utils/streams.ts
Developed as part of the POC for doing schema inference in bigquery, this allows you to examine the first item in an object stream without disrupting the stream. It's probably not going to be used there anymore, but I thought it was generally useful.
> chore: utility for peeking into streams

- packages/core/mappers/object_sync_run.ts
- packages/core/services/object_sync_service.ts
- packages/core/types/object_sync_run.ts
- packages/db/prisma/migrations/20230721181101_merge_syncs/migration.sql
- packages/db/prisma/schema.prisma
based on feedback, merging entity syncs into object syncs table
in future PR, will do renames of prisma model names, but won't touch the columns/table names since that requires a huge migration
> chore: merge entity syncs into object syncs

- apps/mgmt-ui/src/middleware.ts
We have users who get in a state where Clerk isn't returning an orgId for them even when they are part of an org. This gets them stuck where they can't log in without creating another org, which we don't want.
> fix: don't redirect to org creation page

- packages/core/destination_writers/mongodb.ts
- packages/core/remotes/impl/gong/index.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
- packages/core/remotes/impl/salesforce/index.ts
- packages/types/object_record.ts
Looks like this now for hubspot -> mongo
> chore: remove custom hubspot/mongo code and only flatten properties at top level

- packages/core/services/entity_service.ts
- packages/types/entity.ts
because we are going to use `entity_name` in the URL for entity actions
> chore: validate entity name

- packages/core/lib/entity.ts
- packages/core/lib/schema.ts
- packages/core/lib/util.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
- packages/core/remotes/impl/ms_dynamics_365_sales/mappers.ts
- packages/core/remotes/impl/pipedrive/index.ts
- packages/core/remotes/impl/salesforce/index.ts
- packages/core/remotes/utils/properties.ts
- packages/core/services/common_objects/crm/common_object_service.ts
- packages/types/field_mapping_config.ts
- packages/types/object_record.ts
Example of entity sync:
Example with common object sync:
Example with standard object sync:
> feat: put additional fields in a separate key

- packages/core/services/sync_service.ts
> fix: sort syncs by customerId, then providerName, then object

- apps/mgmt-ui/src/components/logs/SyncsTable.tsx
> chore: reverse toggle on syncs page from isPaused to isActive

- packages/core/destination_writers/bigquery.ts
- packages/core/destination_writers/mongodb.ts
- packages/core/destination_writers/postgres.ts
- packages/core/destination_writers/s3.ts
customers will need to drop their existing tables for standard object, custom object, and entity syncs for this to work.
> feat!: start writing _supaglue_last_modified_at to destination

- docs/docs/platform/entities/overview.md
- packages/core/destination_writers/base.ts
- packages/core/destination_writers/bigquery.ts
- packages/core/destination_writers/mongodb.ts
- packages/core/destination_writers/postgres.ts
- packages/core/destination_writers/s3.ts
- packages/core/lib/entity.ts
- packages/core/mappers/entity_record.ts
- packages/core/mappers/object_record.ts
- packages/core/remotes/utils/properties.ts
- packages/core/services/entity_record_service.ts
- packages/core/services/object_record_service.ts
- packages/sync-workflows/activities/sync_entity_records.ts
- packages/sync-workflows/activities/sync_object_records.ts
- packages/types/entity_record.ts
- packages/types/object_record.ts
This also fixes some bugs:
- We were writing `additionalFields` for mongo cache invalidation but `additional_fields` for actual syncing.
- Cache invalidation for entities was broken. We weren't actually invalidating for entity writes.
This is backwards incompatible. We'll need to tell customers to drop their standard/custom/entity sync tables.
I tested this for hubspot -> postgres and hubspot -> mongo syncs. i also tested cache invalidation.
> feat!: write _supaglue_id and _supaglue_additional_fields

- README.md
Replaced a broken link to the list of supported providers in the README
> docs: fixed providers link in README

- packages/core/destination_writers/postgres.ts
- packages/core/remotes/categories/engagement/base.ts
- packages/core/remotes/impl/apollo/index.ts
- packages/core/remotes/impl/salesloft/index.ts
- packages/sync-workflows/activities/sync_object_records.ts
- While retrying calls for 429, we should emit heartbeat so Temporal doesn't kill the activity
- Even if send heartbeats, we may hit the `startToCloseTimeout` for an activity. When that happens, we are screwed. We can set a statement timeout to make sure that postgres eventually cleans up connections.
We should also implement proper connection pooling as a next, but less urgent, step.
> chore: kill sync if takes too long, and provide heartbeats while retrying 429

- packages/core/remotes/impl/outreach/index.ts
- make title stable
- pass all errors back as cause
```
{
"errors": [
{
"title": "Resource Not Found",
"detail": {
"errors": [
{
"id": "resourceNotFound",
"title": "Resource Not Found",
"detail": "Could not find 'prospect' with ID '60386750'."
}
]
},
"problem_type": "NOT_FOUND_ERROR"
}
]
}
```
> fix: improve title and detail error response for outreach

- packages/core/remotes/impl/salesforce/index.ts
empirically jsforce returns three error message formats:
1. "title"
2. `<html>...</html>`
3. "title: json details"
Tested the change to have the the `title` response be the whole string for cases (1) and (2) and the title portion for (3)
> fix: inferred salesforce title

- packages/sync-workflows/workflows/run_object_sync.ts
- bump activity timeout from 10s to 12s
- try to log the inner most cause first
> fix: two run object sync changes

- packages/core/destination_writers/bigquery.ts
We do it for common obj but not for standard / entities
> fix: delete temp table after standard obj syncs

- apps/api/package.json
- apps/mgmt-ui/package.json
- apps/salesforce-pub-sub/package.json
- apps/sync-worker/package.json
- package.json
- packages/core/package.json
- packages/db/package.json
- packages/sync-workflows/package.json
- packages/types/package.json
- packages/utils/package.json
- turbo.json
Can run like this to watch a target and its dependencies:
```
yarn tsc:watch --filter="api..."
```
> chore: add tsc:watch target

- scripts/release.sh
You can speed up local builds by doing
```
yarn turbo login --team Supaglue
yarn turbo link
```
Be sure to select `Supaglue` as the scope to link.
> fix: upload sentry sourcemaps

- apps/api/index.ts
- apps/api/middleware/api_key.ts
- apps/api/middleware/pino_context.ts
- apps/api/routes/actions/index.ts
- apps/api/routes/crm/index.ts
- apps/api/routes/data/index.ts
- apps/api/routes/engagement/index.ts
- apps/api/routes/marketing-automation/index.ts
- apps/api/routes/metadata/v2/index.ts
- apps/api/routes/mgmt/v2/index.ts
- Empirically verified that context.X isn't in the output
- Didn't dig into pino-context code, but used trial-and-error/process of elimination to see under what situations it is logged in the output: using `addLogContext` after all the other middleware seems to work
```
supaglue-api-1          |     context: {
supaglue-api-1          |       "applicationEnv": "production",
supaglue-api-1          |       "applicationName": "My Application",
supaglue-api-1          |       "applicationId": "4acf8358-db1f-4dfa-8c3c-357106afc1a7",
supaglue-api-1          |       "orgId": "e7070cc8-36e7-43e2-81fc-ad57713cf2d3"
supaglue-api-1          |     }
```
> fix: log context for api

- apps/api/routes/mgmt/v2/sync_run/index.ts
- packages/types/sync_run.ts
- MUI data grid x let's you filter on any attribute so allow that on the backend
Tested this locally
> fix: sync log filter

- packages/core/errors.ts
- packages/core/lib/apollo_ratelimit.ts
- packages/core/lib/ratelimit.ts
- packages/core/remotes/impl/apollo/index.ts
- packages/core/remotes/utils/paginator.ts
- packages/sync-workflows/activities/sync_object_records.ts
- packages/sync-workflows/workflows/run_object_sync.ts
- Don't retry workflow for `syncObjectRecords` activity to avoid draining api quota
- Apollo is special. Use its own ratelimit function
- Abort retry and fail the workflow on hourly, daily, free plan rate limits
- Increase Apollo page size
- Allow our streams to abort early on certain errors
- Fix Apollo paginating for edge case: no data
- Synced 202 records while paginating
- Failed on hourly/daily rate limit early
> fix: apollo sync improvements, paginator stream changes

- apps/mgmt-ui/src/components/settings/WebhookTabPanel.tsx
- apps/mgmt-ui/src/pages/api/index.ts
- apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
- apps/mgmt-ui/src/pages/applications/[applicationId]/settings/[...tab].tsx
Context: we are calling a Svix call on every `getServerSideProps`, even on pages that don't need it. This is adding ~200-300ms of latency to each page load.
I've refactored it to move the Svix call to just that tab only. This requires moving the Svix API key to `NEXT_PUBLIC_...`
> chore: refactor svix away from getServerSideProps

- Dockerfile.dev
- apps/api/index.ts
- depot.json
- docker-compose.yml
Once this lands, use `docker compose watch` to start the stack. If you want to watch logs, use `docker compose logs -f`
Note: first start will take a while as it builds images
> chore: use docker compose watch for local dev

- apps/api/middleware/openapi.ts
These should be warnings as they flood the logs making it hard to identify true errors that customers are seeing.
> chore: change response validation errors to warnings to reduce noise

- apps/api/routes/actions/v2/index.ts
- apps/api/routes/metadata/v2/index.ts
- apps/api/routes/mgmt/v2/index.ts
This middleware should be used anywhere we use the open api validation middleware. It was missing from a few places, and that means that requests that should have returned a 400 were returning a 500 instead.
> fix: add openApiErrorHandlerMiddleware to places it's missing from

- apps/mgmt-ui/src/pages/applications/[applicationId]/customers/[customerId]/connections/[providerName]/index.tsx
Hubspot API does not allow lookup by ID (expects name) -- not sure how this was ever working.
Note: For any customers that have already mapped entities to custom objects, they will have to remap them.
> fix: custom object entity mappings

- apps/mgmt-ui/src/pages/applications/[applicationId]/customers/index.tsx
The free `DataGrid` only displays 100 rows. The paid version will display more.
In the future we should probably paginate + support search/filtering capabilities.
> fix: customers table should display all customers

- apps/api/routes/crm/v2/account.integration.test.ts
- apps/api/routes/crm/v2/contact.integration.test.ts
- apps/api/routes/crm/v2/lead.integration.test.ts
Pipedrive has no read after write guarantees, so we should wait before doing the GET to check its values.
> chore: fix flaky integration tests for pipedrive

- docs/docs/tutorials/transformations/object-field-mapping.mdx
- packages/core/destination_writers/base.ts
- packages/core/destination_writers/postgres.ts
- packages/core/destination_writers/postgres_impl.ts
- packages/core/destination_writers/supaglue.ts
- packages/sync-workflows/activities/sync_object_records.ts
Manually tested this works for both custom objects and standard objects in both managed sync and customer postgres settings. Did not implement this for postgres so did not test its implementation. 
  | Standard Objects | Custom Objects
-- | -- | --
Managed sync | Tested ✅ | Tested ✅
Customer postgres | Tested ✅ | Tested ✅
Customer bigQuery | No change | No change
Also tested that that this works for the custom object lists endpoint when using Supaglue managed destination (thanks to the views)
https://github.com/supaglue-labs/supaglue/assets/696842/d1c6060d-82be-47aa-a7a3-ec6cfba6ea0e
> feat: write custom objects into a single table and create convenience views

- packages/core/lib/postgres.ts
This was the only missing piece to make managed syncs work for engagement.
> fix: missing partitions for contacts and sequence states

- apps/api/integration-test-environment.js
- apps/api/routes/crm/v2/metadata/custom_objects/custom_objects.integration.test.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/salesforce/mappers.ts
This also includes some bug fixes:
- Hubspot adding a required field
- Fail fast when deleting fields (Hubspot does not allow this)
- GET for Salesforce had incorrect information
This does NOT test creation of custom object records. That is coming soon.
> fix: custom objects API + integration tests

- apps/api/integration-test-environment.js
- apps/api/routes/engagement/v2/sequence.integration.test.ts
- packages/core/remotes/impl/salesloft/mappers.test.ts
- packages/core/remotes/impl/salesloft/mappers.ts
> feat: Sequence integration tests

- apps/api/integration-test-environment.js
- apps/api/routes/crm/v2/custom_objects/custom_object_records.integration.test.ts
- apps/api/routes/crm/v2/custom_objects/index.ts
- apps/api/routes/crm/v2/metadata/custom_objects/custom_objects.integration.test.ts
- packages/core/remotes/impl/hubspot/index.ts
This also includes some bugfixes on the relevant code:
- PATCH should return 200 not 201
- Missing required fields in hubspot should return 400 not 500
> fix!: custom object records integration tests

- apps/api/routes/actions/v2/index.ts
- apps/api/services/passthrough_service.ts
- packages/core/lib/logger.ts
- packages/core/lib/webhook.ts
- packages/core/remotes/base.ts
- packages/core/remotes/impl/6sense/index.ts
- packages/core/remotes/impl/apollo/index.ts
- packages/core/remotes/impl/clearbit/index.ts
- packages/core/remotes/impl/gong/index.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/intercom/index.ts
- packages/core/remotes/impl/marketo/index.ts
- packages/core/remotes/impl/outreach/index.ts
- packages/core/remotes/impl/pipedrive/index.ts
- packages/core/remotes/impl/salesforce_marketing_cloud_account_engagement/index.ts
- packages/core/remotes/impl/salesloft/index.ts
- packages/core/remotes/impl/slack/index.ts
- packages/core/remotes/sg_axios.ts
log axios error responses for remote providers:
```
supaglue-api-1          | [22:42:15.316] WARN: axios request failed
supaglue-api-1          |     context: {
supaglue-api-1          |       "applicationEnv": "development",
supaglue-api-1          |       "applicationName": "My Application",
supaglue-api-1          |       "applicationId": "a5398e5c-3f64-4b41-9cc1-cffeee9dfb0a",
supaglue-api-1          |       "orgId": "org_2OO0cz8xFHmux421XdlbnWQ9OrS"
supaglue-api-1          |     }
supaglue-api-1          |     err: {
supaglue-api-1          |       "message": "Request failed with status code 400",
supaglue-api-1          |       "name": "AxiosError",
supaglue-api-1          |       "stack":
supaglue-api-1          |           AxiosError: Request failed with status code 400 …
```
> chore: more logs for axios and passthrough for debuggability

- packages/core/remotes/impl/hubspot/mappers.ts
Don't need these anymore after we implemented the flattening everywhere.
> chore: remove obsolete association mapper

- apps/api/Dockerfile.dev
- apps/sync-worker/Dockerfile.dev
- docker-compose.override.watch.yml
To use, `cp docker-compose.override.watch.yml docker-compose.override.yml` and run `docker compose watch`
Make sure you are on Docker Desktop version >= 4.25.0
> chore: optional docker compose config override for use with docker compose watch

- apps/api/integration-test-environment.js
- apps/api/routes/crm/v2/metadata/custom_objects/custom_objects.integration.test.ts
We aren't able to properly cleanup due to permissions issues.
> chore: disable salesforce custom objects integration tests

- packages/core/destination_writers/postgres_impl.ts
- push deduping to first stream instead of at DB query time into final table
- Tested against Hubspot with Supaglue common and standard objects
- Tested archiving, unarchiving and setting the page limit to 1 so archive/unarchive events happen across pages
> chore: dedupe in first stream step for perf improvement

- apps/mgmt-ui/package.json
- apps/mgmt-ui/src/components/connectors/provider/ProviderDetailsPanel.tsx
- apps/mgmt-ui/src/components/connectors/provider/ProviderTabPanelContainer.tsx
- apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx
- apps/mgmt-ui/src/hooks/useLekkoConfigs.ts
- apps/mgmt-ui/src/layout/Navigator.tsx
- apps/mgmt-ui/src/pages/api/internal/lekko/index.ts
- apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
- apps/mgmt-ui/src/utils/lekko.ts
- yarn.lock
Fixes: #### 
- Upgraded Lekko node server SDK: 0.0.9 -> 0.2.0
- Moved Lekko config fetches from getServerSideProps (which caused delays on each page load, see #1840) to an API route
- API route is at /api/internal/lekko and currently fetches all configs
- Cleaned up to remove home CTA button configs which seem to not be used anymore
- Added hook for querying new Lekko API route
- Updated relevant components to use new hook
- Tested locally
> chore: switch Lekko SDK usage from server props to API route

- packages/core/destination_writers/postgres_impl.ts
- Instead of copy everything to a physical second temp table, just select from the first since we have the necessary indexes on it already
> chore: select from original temp table instead of copy into second

- apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigListPanel.tsx
> fix: sync configs list UI

- packages/core/remotes/impl/salesforce/index.ts
I see these from time to time in our logs. These should all be 400s -- I feel comfortable doing so since Salesforce is one of our most tested providers.
> chore: remap salesforce error codes

- packages/core/remotes/base.ts
- packages/core/remotes/categories/crm/index.ts
- packages/core/remotes/categories/engagement/base.ts
- packages/core/remotes/categories/engagement/index.ts
- packages/core/remotes/categories/enrichment/base.ts
- packages/core/remotes/categories/enrichment/index.ts
- packages/core/remotes/categories/marketing_automation/index.ts
- packages/core/remotes/categories/no_category/base.ts
- packages/core/remotes/categories/no_category/index.ts
- packages/core/remotes/impl/apollo/index.ts
- packages/core/remotes/impl/hubspot/index.ts
- packages/core/remotes/impl/marketo/index.ts
- packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
- packages/core/remotes/impl/outreach/index.ts
- packages/core/remotes/impl/pipedrive/index.ts
- packages/core/remotes/impl/salesforce/index.ts
- packages/core/remotes/impl/salesforce_marketing_cloud_account_engagement/index.ts
- packages/core/remotes/impl/salesloft/index.ts
- packages/core/remotes/index.ts
- packages/sync-workflows/workflows/run_object_sync.ts
Add autopauses for:
- revoked Apollo API Keys
- getaddrinfo ENOTFOUND for Microsoft
- resource not found for Salesforce (indicates permission issue)
This also fixes error handling for Microsoft in general
> chore: more autopauses

- apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx
- packages/core/services/sync_config_service.ts
Also fix a UI bug where you weren't able to create new SyncConfigs in the UI with custom objects (but you could update them after the fact).
Currently, the API will not allow you to delete Sync Configs for which there are existing syncs (you have to delete the connections, or all the objects).
> feat: allow sync config deletions even when there are existing syncs

- packages/core/remotes/impl/outreach/index.ts
Just something I noticed while looking at code
> fix: don't swallow errors in outreach

- packages/core/remotes/impl/salesloft/index.ts
Still seeing a customer getting syncs failing due to salesloft rate limits, so bumping the min wait time for retry.
> fix: wait even longer after salesloft rate limit

- apps/api/Dockerfile
- apps/api/tsconfig.json
- apps/sync-worker/Dockerfile
- apps/sync-worker/tsconfig.build.json
This should allow stack traces to have the correct typescript line numbers in logs.
> chore: include sourcemaps in images and configure node to use them

- docs/docs/platform/managed-auth.mdx
- docs/docs/providers/salesforce.mdx
> docs: update salesforce provider to include managed auth for sandboxes

- apps/api/routes/engagement/v2/account.ts
- apps/api/routes/engagement/v2/contact.ts
- apps/api/routes/engagement/v2/mailbox.ts
- apps/api/routes/engagement/v2/sequence.ts
- apps/api/routes/engagement/v2/sequence_state.ts
- apps/api/services/managed_data_service.ts
- packages/core/remotes/impl/apollo/mappers.test.ts
- packages/core/remotes/impl/apollo/mappers.ts
You still need to use passthrough to look up the custom field IDs, but this is better than not supporting it at all.
Also noticed that we weren't respecting the `include_raw_data` flag for engagement, so this also fixes this.
> feat: support custom field updating for apollo

- packages/core/lib/pagination.test.ts
- packages/core/lib/pagination.ts
- packages/core/package.json
- yarn.lock
Reason: for developers using http clients (like axios) this may result in double-url-encoding which will lead to 500s.
> fix: revert "feat!: URL-encode cursors"

- packages/db/prisma/migrations/20231201002644_cascade_delete_sync_configs/migration.sql
- packages/db/prisma/schema.prisma
This will make it so that the only thing blocking deleting applications (or anything) will be existing connections and/or syncs.
> chore: cascade delete sync configs

- apps/api/routes/mgmt/v2/sync/index.ts
- apps/mgmt-ui/src/components/logs/SyncsTable.tsx
- apps/mgmt-ui/src/components/syncs/SyncsListPanel.tsx
- apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigListPanel.tsx
- apps/mgmt-ui/src/utils/datetime.ts
- apps/mgmt-ui/src/utils/syncConfig.ts
- packages/core/mappers/sync.ts
- packages/core/services/sync_service.ts
- packages/sync-workflows/services/sync_service.ts
- packages/types/index.ts
- packages/types/snakecased_keys.ts
- packages/types/sync.ts
- packages/types/sync_config.ts
- surface frequency, period full, and strategy on sync page (respecting inheritance), associations to sync
- breaking change: snakecased `related_sync_states`
- removed entity names from syncs so there's more room
note: we should move to using classes for Supaglue's core concepts for better encapsulation (we have a lot of loose functions in different places)
- tested locally
> feat!: surface default and override sync strategies

- apps/mgmt-ui/src/layout/Header.tsx
> fix: add back logic to hide banner

- packages/core/remotes/utils/paginator.ts
Node documentation indicates that this is the correct way to indicate errors in a stream and not to use `.emit('error', ...)` as that is internal to streams.
I'm hoping this will fix some cases were we aren't getting errors handled by the `handleErr` function in the provider.
> fix: stream error handling

- packages/db/prisma/migrations/20231213001527_add_back_cascade/migration.sql
- packages/db/prisma/schema.prisma
To more easily delete applications.
> chore: add back cascade
