README.md
docs/docs/tutorial.md
docs/versioned_docs/version-0.1.0/tutorial.md

- fix some broken links in readme
- center readme links at top
- iterate on tutorial to embed a component after sample-app is up

fix(docs): fix readme links, tutorial iteration

---

docs/docusaurus.config.js
docs/package.json
yarn.lock

docs: analytics on docs

---

.github/workflows/api_build_docker.yml
.github/workflows/ci.yml
.github/workflows/docker_build_and_push.yml
.yarnrc.yml
apps/api/package.json
apps/cli/package.json
apps/sample-app/package.json
package.json
packages/nextjs/package.json
packages/sdk/package.json
turbo.json
yarn.lock

Runs linters, builds, and runs tests (when we have them) on pushes and pull requests.
For the API workspace, also builds a docker image.

chore: test builds for CI

---

README.md
apps/api/package.json
apps/cli/package.json
packages/nextjs/package.json
packages/sdk/package.json
turbo.json

Fixes ENG-100
also:
* fix: slack link in README header
* fix: speed up builds

chore: add CI badge to readme

---

docs/versioned_docs/version-0.1.x/react-components.md
packages/nextjs/src/components/Switch/Switch.tsx

- Also changes default of `includeSyncDescription` to false.

chore: update docs to reflect new Switch props

---

package.json
packages/nextjs/src/providers/SupaglueProvider.tsx
yarn.lock

fix(sample-app): fix api url

---

docs/src/components/BrowserWindow/styles.module.css

docs: remove image padding in browserWindow

---

apps/api/routes/sync.ts
apps/api/syncs/entities/sync_run_mapper.ts
apps/api/syncs/services/sync_service.ts
apps/api/temporal/workflows/run_sync.ts

feat(api): endpoint to get sync run logs

---

apps/api/temporal/activities/do_sync.ts
apps/sample-app/supaglue-config/common/contact.ts
apps/sample-app/supaglue-config/inbound/contact.ts
apps/sample-app/supaglue-config/outbound/contact.ts
apps/sample-app/supaglue-config/postgres_credentials.ts
packages/sdk/src/base.ts
packages/sdk/src/destinations/postgres.ts
packages/sdk/src/destinations/webhook.ts
packages/sdk/src/index.ts
packages/sdk/src/internalIntegrations/base.ts
packages/sdk/src/internalIntegrations/index.ts
packages/sdk/src/internalIntegrations/postgres.ts
packages/sdk/src/internalIntegrations/webhook.ts
packages/sdk/src/sources/postgres.ts

welcome suggestions on better organization of directory structure

fix: remove guard for outbound sync and refactor sdk types so that source/destination postgres share creds

---

docs/docs/intro.md
docs/versioned_docs/version-0.1.x/intro.md

- unnecessary admonition
- add outbound use case to next docs

docs(intro): clarify use case

---

.github/workflows/ci.yml
package.json
yarn.lock

Also upgrades `turbo` to latest version

chore: only run ci for changed packages

---

apps/api/developer_config/entities/developer_config.ts
apps/api/prisma/migrations/20230209224703_sync_source_destination/migration.sql
apps/api/prisma/schema.prisma
apps/api/syncs/entities/sync.ts
apps/api/temporal/activities/do_sync.ts
apps/api/temporal/sdk/customer_integrations/salesforce.ts
apps/sample-app/supaglue-config/outbound/contact.ts
docs/docs/tutorial.md

this allows the customer to select a salesforce object if requested by the developer

feat: customer-selectable salesforce object; needs cleanup

---

apps/api/package.json
apps/sample-app/package.json
yarn.lock

chore: update prisma version

---

apps/sample-app/pages/integrations/[type].tsx
docs/docs/tutorial.md
docs/package.json
yarn.lock

docs: remove customizing react components from tutorial

---

apps/sample-app/hooks.ts
apps/sample-app/styles/globals.css

fix(sample-app): fix hydration

---

apps/api/routes/field.ts
apps/sample-app/pages/_app.tsx
apps/sample-app/pages/integrations/[type].tsx
apps/sample-app/supaglue-config/index.ts
apps/sample-app/supaglue-config/outbound/contact.ts
packages/nextjs/src/components/SyncConfigCard/SyncConfigCard.tsx
packages/nextjs/src/components/SyncConfigCard/styles.ts
packages/nextjs/src/elements/FieldMapping/FieldMapping.tsx
packages/types/src/util.ts

fix: support outbound sync in ui

---

README.md
docs/docs/intro.md

docs: fix intro and readme

---

apps/api/lib/posthog.ts
apps/api/routes/oauth.ts
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/index.ts
packages/core/services/remote_service.ts
packages/sync-workflows/activities/do_sync.ts
packages/sync-workflows/workflows/run_syncs.ts

Move oauth/client config for connectors to the same place for ease of extension

feat: move oauth/client to same place

---

packages/db/prisma/migrations/20230302220746_fix_typo/migration.sql
packages/db/prisma/schema.prisma

This may cause data loss. YMMV

fix: db schema typo

---

docker-compose.yml

fix: init env

---

apps/api/middleware/connection.ts
apps/api/middleware/customer.ts
apps/api/middleware/integration.ts
apps/api/routes/customer/index.ts
apps/api/routes/customer/integration/connection/index.ts
apps/api/routes/customer/integration/index.ts
apps/api/routes/index.ts
apps/api/types/express.d.ts
packages/core/dependency_container.ts
packages/core/mappers/customer.ts
packages/core/mappers/index.ts
packages/core/services/connection_service.ts
packages/core/services/customer_service.ts
packages/core/services/index.ts
packages/core/services/integration_service.ts
packages/core/types/customer.ts
packages/core/types/integration.ts

- add missing service and endpoints for customer, integration, connection concepts
- add middleware for capturing params
TODO
- revise customer schema
- openapi schema
- mgmt ui

feat: first pass for application mgmt apis

---

packages/core/package.json
packages/core/remotes/crm/salesforce/index.ts
yarn.lock

Somehow jsforce was hanging on bulk 2.0 query. didn't debug and just rewrote it with `fetch`.
This does not yet deal with refreshing access token.

fix: sf bulk 2.0

---

apps/sync-worker/index.ts

previously, error stacktraces were not being logged because temporal worker logs the error object under the `error` key in `LogMetadata`. However, `pino` expects error object to be under `err` key.

fix: log error stacktraces in sync-worker

---

apps/sync-worker/dependency_container.ts
packages/core/lib/webhook.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/base_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/sync-workflows/activities/do_sync.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts
packages/sync-workflows/workflows/run_syncs.ts

Also log # records updated in webhook

feat: webhooks for sync finish

---

DEVELOPMENT.md

Comment about matching internal token

docs: update fe docs

---

packages/sync-workflows/workflows/run_syncs.ts

fix: emit webhook/sync log after associations

---

apps/api/routes/internal/v1/customer/index.ts
apps/api/routes/mgmt/v1/customer/index.ts
openapi/mgmt/components/schemas/objects/customer.yaml
openapi/mgmt/openapi.bundle.json
openapi/mgmt/paths/customers.yaml
openapi/mgmt/paths/customers@{customer_id}.yaml
packages/core/services/customer_service.ts
packages/schemas/gen/mgmt.ts

Also `list` by application only

fix: expose external id only for `/customers` endpoints

---

DEVELOPMENT.md
apps/mgmt-ui/.env.sample
apps/mgmt-ui/scripts/start_dev.sh
docker-compose.override.dev.yml
docker-compose.yml

fix: start management ui as part of docker compose up

---

apps/mgmt-ui/src/pages/customers/index.tsx

fix: customerId

---

docs/docs/guides/authentication.md
docs/docs/guides/embedded-links.mdx
docs/docs/guides/pagination.md

docs: add more guides

---

apps/api/routes/crm/v1/opportunity.ts
openapi/crm/openapi.bundle.json
openapi/crm/openapi.yaml
openapi/crm/paths/opportunities@_search.yaml
packages/core/services/common_models/opportunity_service.ts
packages/core/types/crm/opportunity.ts
packages/schemas/crm.ts
packages/schemas/gen/crm.ts

feat: support searching opportunities by accountId

---

docs/docs/quickstart.mdx
openapi/crm/components/schemas/objects/account.yaml
openapi/crm/components/schemas/objects/contact.yaml
openapi/crm/components/schemas/objects/lead.yaml
openapi/crm/components/schemas/objects/opportunity.yaml
openapi/crm/components/schemas/objects/user.yaml
openapi/crm/openapi.bundle.json
openapi/crm/paths/accounts.yaml
openapi/crm/paths/accounts@_search.yaml
openapi/crm/paths/accounts@{account_id}.yaml
openapi/crm/paths/contacts.yaml
openapi/crm/paths/contacts@_search.yaml
openapi/crm/paths/leads.yaml
openapi/crm/paths/opportunities.yaml
openapi/crm/paths/opportunities@_search.yaml
openapi/crm/paths/opportunities@{opportunity_id}.yaml
openapi/crm/paths/users.yaml
packages/core/mappers/account.ts
packages/core/mappers/contact.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/mappers/user.ts
packages/core/types/crm/account.ts
packages/core/types/crm/contact.ts
packages/core/types/crm/lead.ts
packages/core/types/crm/opportunity.ts
packages/core/types/crm/user.ts
packages/schemas/gen/crm.ts

feat: support remote_id in response payload + some docs fixes

---

apps/api/middleware/connection.ts
apps/api/routes/internal/v1/application/index.ts
apps/api/routes/internal/v1/customer/connection/index.ts
apps/api/routes/internal/v1/customer/index.ts
apps/api/routes/internal/v1/integration/index.ts
apps/api/routes/mgmt/v1/customer/connection/index.ts
apps/api/routes/mgmt/v1/customer/index.ts
apps/api/routes/mgmt/v1/integration/index.ts
openapi/mgmt/components/schemas/create_update_customer.yaml
openapi/mgmt/components/schemas/create_update_integration.yaml
openapi/mgmt/openapi.bundle.json
openapi/mgmt/paths/connections@{connection_id}.yaml
packages/core/services/connection_service.ts
packages/core/services/integration_service.ts
packages/core/types/integration.ts
packages/schemas/gen/mgmt.ts

phase 1. there are still unaddressed areas

chore: protect unauthorized access to routes by checking application

---

helm/GKE_RUNBOOK.md

https://github.com/supaglue-labs/supaglue/issues/407

docs: upgrade instructions for 0.6.0

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx

fix: expose application id in mgmt ui

---

packages/db/prisma/migrations/20230324183558_add_syncs/migration.sql
packages/db/prisma/schema.prisma

https://github.com/supaglue-labs/supaglue/issues/306

feat: add syncs table for high watermark tracking for incremental syncs

---

apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/components/Spinner/index.tsx
apps/mgmt-ui/src/components/configuration/IntegrationCard.tsx
apps/mgmt-ui/src/components/configuration/IntegrationDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/IntegrationTabPanelContainer.tsx
apps/mgmt-ui/src/components/configuration/IntegrationsTabPanel.tsx
apps/mgmt-ui/src/pages/api/internal/integrations/create.ts

Also:
- added loading states in various related pages
- changed redirects to already include applicationId scoping for faster redirects
https://www.loom.com/share/a026a7eec0d4465f885a7270fcf146f0

feat: create integrations in UI

---

apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx

https://www.loom.com/share/492b5981459040f09a59572e2655df9c

fix: webhook UI cache

---

openapi/crm/components/schemas/objects/addresses.yaml
openapi/crm/openapi.bundle.json
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/types/base.ts
packages/schemas/gen/crm.ts

* also makes `street2` optional in openAPI spec

feat: Salesforce feature parity (email/address/phone, owner associations, custom_field writes)

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx

See https://github.com/mui/material-ui/issues/36133 for why we need to do this

fix: new application text field shouldn't blur on certain characters

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx
apps/mgmt-ui/src/components/logs/LogsTable.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/sync_logs/index.tsx

- more loading states
- handle empty timestamps in sync logs

fix: misc management ui fixes

---

apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
apps/mgmt-ui/src/pages/create-organization/[[...index]].tsx
apps/mgmt-ui/src/pages/sign-in/[[...index]].tsx
apps/mgmt-ui/src/pages/sign-up/[[...index]].tsx

https://www.loom.com/share/65ad9c2fbf1e405db93a9c6aebfd379b

fix: fix sign-up flow

---

openapi/crm/components/schemas/create_update_account.yaml
openapi/crm/components/schemas/create_update_contact.yaml
openapi/crm/components/schemas/objects/account.yaml
openapi/crm/components/schemas/objects/contact.yaml
openapi/crm/components/schemas/objects/lifecycle_stage.yaml
openapi/crm/openapi.bundle.json
openapi/crm/openapi.yaml
packages/core/mappers/account.ts
packages/core/mappers/contact.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/types/base.ts
packages/core/types/crm/account.ts
packages/core/types/crm/contact.ts
packages/db/prisma/migrations/20230329181151_lifecycle_stage/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/gen/crm.ts

feat: support lifecyclestage for accounts and contacts (hubspot only)

---

packages/core/mappers/account.ts
packages/core/mappers/contact.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/mappers/user.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/core/services/common_models/user_service.ts
packages/core/types/crm/account.ts
packages/core/types/crm/contact.ts
packages/core/types/crm/lead.ts
packages/core/types/crm/opportunity.ts
packages/core/types/crm/user.ts
packages/db/prisma/migrations/20230329223900_remote_deleted_at/migration.sql
packages/db/prisma/schema.prisma

https://github.com/supaglue-labs/supaglue/issues/489
This does not yet actually pull in deleted records from hubspot. It just lays the groundwork to be able to pull it in, by defining the types.

chore: add new DB columns and types to track deleted_at ts

---

DEVELOPMENT.md
apps/mgmt-ui/.env.sample
apps/mgmt-ui/src/middleware.ts
apps/mgmt-ui/src/pages/api/auth/[...nextauth].ts
apps/mgmt-ui/src/pages/index.tsx
docker-compose.yml

Fixes locally running development environment
Logged in locally using next-auth

fix: local nextauth

---

docs/docs/getting-started.mdx

Update the curl for creating a customer

docs: fix curl for creating customer

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx

fix: menu item link

---

package.json
turbo.json
yarn.lock

fix: add package.json to turbo globalDependencies

---

apps/api/dependency_container.ts
apps/api/middleware/api_key.ts
apps/api/routes/internal/v1/application/index.ts
apps/api/routes/internal/v1/webhook/index.ts
apps/api/routes/mgmt/v1/webhook/index.ts
apps/api/services/application_service.ts
apps/api/services/connection_writer_service.ts
apps/api/services/index.ts
apps/api/services/sync_service.ts
apps/sync-worker/dependency_container.ts
apps/sync-worker/services/application_service.ts
apps/sync-worker/services/index.ts
packages/core/dependency_container.ts
packages/core/services/index.ts
packages/sync-workflows/activities/get_sync.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts

Fixes: https://github.com/supaglue-labs/supaglue/issues/500
BE only

feat: allow updating and deleting application

---

packages/sync-workflows/activities/get_sync.ts

fix: remove code that purposely fails get sync

---

apps/mgmt-ui/next.config.js
apps/mgmt-ui/src/pages/_app.tsx

Do some tree-shaking to improve mgmt-ui loading times locally in development. there's probably more to do, but it went down from about 18-20 seconds on my laptop to 2-3 seconds.

chore: improve mgmt ui performance locally

---

apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/components/ApplicationMenu/index.tsx
apps/mgmt-ui/src/pages/api/internal/applications/[...applicationId].ts

feat: allow update name and delete for application

---

apps/api/routes/internal/v1/application/index.ts
apps/api/services/application_service.ts
apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/pages/api/internal/applications/index.ts
apps/mgmt-ui/src/pages/index.tsx
packages/types/application.ts

Fixes: #### 
We should upsert application to avoid race instead of creating since we have a unique constraint on `name, orgId`
Tested locally

fix: upsert application to avoid race

---

packages/db/prisma/migrations/20230404211747_sync_change/migration.sql
packages/db/prisma/schema.prisma

Fixes: https://github.com/supaglue-labs/supaglue/issues/437

chore: create SyncChange table which will help with eventual consistency for syncs

---

apps/api/routes/mgmt/v1/index.ts
apps/api/services/connection_writer_service.ts
packages/core/mappers/connection.ts
packages/core/services/connection_service.ts
packages/db/prisma/migrations/20230404212216_connection_remote_id_non_nullable/migration.sql
packages/db/prisma/schema.prisma

chore: cleanup connection remote ids

---

packages/db/prisma/migrations/20230404215302_sync_no_cascade/migration.sql
packages/db/prisma/schema.prisma

Fixes: https://github.com/supaglue-labs/supaglue/issues/437

chore: do not delete cascade for syncs

---

packages/core/remotes/crm/hubspot/index.ts

fix: don't fail hubspot syncs due to unimplemented events 

---

package.json
packages/db/package.json
packages/sync-workflows/workflows/run_sync.ts
yarn.lock

Fixes: #### 
When we added `event`, old sync states weren't updated.

fix: include new maxLastModifiedAtMsMap entry for new common models

---

packages/core/services/common_models/base_service.ts
packages/sync-workflows/workflows/run_sync.ts

chore: add logs for better debugging for importing records

---

packages/core/services/common_models/account_service.ts
packages/core/services/common_models/base_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/event_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/core/services/common_models/user_service.ts
packages/sync-workflows/activities/import_records.ts

fix: paginate upsert from temp table

---

packages/core/services/common_models/base_service.ts

chore: cheaper row count

---

packages/core/remotes/crm/salesforce/index.ts

fix: salesforce rate limit error code

---

apps/mgmt-ui/src/components/logs/LogsTable.tsx
packages/core/services/sync_history_service.ts

fix: sort sync logs in UI by timestamp

---

packages/core/lib/webhook.ts

Fixes: #### 
Tested locally
```
{
"data": {
"type": "SYNC_SUCCESS",
"payload": {
"connection_id": "455d2989-6d70-482d-8867-4477092cb4de",
"customer_id": "external-customer-hubspot",
"provider_name": "hubspot",
"history_id": "c7765531-3fd5-4192-80b9-649132ee85f3",
"num_records_synced": 0,
"common_model": "opportunity"
}
},
"headers": {
"Content-Type": "application/json"
}
}
```

fix: webhook header casing

---

packages/core/lib/webhook.ts

fix: webhook

---

packages/core/remotes/crm/salesforce/index.ts

chore: disable events for now

---

apps/api/routes/oauth.ts

feat: allow login url to be specified

---

openapi/mgmt/components/schemas/objects/connection.yaml
openapi/mgmt/openapi.bundle.json
openapi/mgmt/paths/connections.yaml
packages/schemas/gen/mgmt.ts
packages/types/webhook.ts

docs: document connection remote_id

---

packages/core/remotes/crm/hubspot/index.ts

fix: Fix hubspot incremental syncs when >10k records have been updated

---

apps/api/routes/internal/v1/customer/connection/index.ts
apps/api/routes/mgmt/v1/customer/connection/index.ts
apps/api/services/connection_and_sync_service.ts
openapi/mgmt/components/schemas/create_update_connection.yaml
openapi/mgmt/openapi.bundle.json
openapi/mgmt/paths/connections.yaml
packages/core/services/connection_service.ts
packages/schemas/gen/mgmt.ts
packages/schemas/mgmt.ts

1. Support create connection
2. Fix delete connection

feat: mgmt endpoint to create connection and fix delete connection

---

packages/core/lib/webhook.ts
packages/sync-workflows/workflows/run_sync.ts

fix: increase webhook timeout

---

apps/api/services/connection_and_sync_service.ts
packages/core/lib/crypt.ts
packages/core/mappers/connection.ts
packages/core/mappers/integration.ts
packages/core/services/connection_service.ts
packages/core/services/integration_service.ts

fix: async crypt for event loop lag

---

apps/api/middleware/connection.ts
packages/core/services/connection_service.ts

fix: avoid decrypting integration on every request

---

apps/api/routes/crm/v1/account.ts
apps/api/routes/crm/v1/contact.ts
apps/api/routes/crm/v1/event.ts
apps/api/routes/crm/v1/lead.ts
apps/api/routes/crm/v1/opportunity.ts
apps/api/routes/crm/v1/user.ts
packages/core/mappers/account.ts
packages/core/mappers/address.ts
packages/core/mappers/contact.ts
packages/core/mappers/email_address.ts
packages/core/mappers/event.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/mappers/phone_number.ts
packages/core/mappers/user.ts
packages/utils/snakecase.ts

Fixes: https://github.com/supaglue-labs/supaglue/issues/595
Hopefully this improves event loop lag

chore: use explicit mappers for common model snakecasing for big performance improvement

---

packages/core/remotes/crm/salesforce/index.ts

chore: add salesforce poll logs

---

apps/api/routes/internal/v1/customer/connection/index.ts
apps/api/routes/mgmt/v1/customer/connection/index.ts
packages/core/services/connection_service.ts
packages/schemas/mgmt.ts

Fixes: https://github.com/supaglue-labs/supaglue/issues/615

fix: filter connections only for a given customer

---

apps/api/services/application_service.ts
packages/core/services/connection_service.ts
packages/core/services/customer_service.ts

Fixes: https://github.com/supaglue-labs/supaglue/issues/594

chore: better error message for deleting apps/customers without deleting connections

---

packages/core/remotes/crm/hubspot/index.ts

Fixes: https://github.com/supaglue-labs/supaglue/issues/616

fix: filter out hubspot objects that have been deleted for a while

---

apps/sync-worker/services/sync_service.ts
packages/core/services/integration_service.ts
packages/db/prisma/migrations/20230412231743_integration_changes/migration.sql
packages/db/prisma/schema.prisma

Fixes: https://github.com/supaglue-labs/supaglue/issues/552

fix: update existing syncs' schedules when integration sync period is updated

---

apps/api/routes/crm/v1/opportunity.ts
openapi/crm/components/schemas/objects/account.yaml
openapi/crm/components/schemas/objects/contact.yaml
openapi/crm/components/schemas/objects/event.yaml
openapi/crm/components/schemas/objects/lead.yaml
openapi/crm/components/schemas/objects/opportunity.yaml
openapi/crm/components/schemas/objects/user.yaml
openapi/crm/openapi.bundle.json
packages/core/lib/pagination.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/base_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/event_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/core/services/common_models/user_service.ts
packages/core/services/sync_history_service.ts
packages/db/prisma/migrations/20230412233756_unique_last_modified_at_id/migration.sql
packages/db/prisma/migrations/20230413174514_unique_last_modified_at_id/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/gen/crm.ts
packages/types/crm/account.ts
packages/types/crm/base.ts
packages/types/crm/contact.ts
packages/types/crm/event.ts
packages/types/crm/index.ts
packages/types/crm/lead.ts
packages/types/crm/opportunity.ts
packages/types/crm/user.ts

Fixes: #617
* paginate by last modified at then id
* this also requires making last modified at non-nullable
* some cleanups / fixes to existing code -- e.g. we were not writing last_modified_at in the creation path
Testing locally

feat: paginate by last modified at, then id

---

apps/api/routes/internal/v1/customer/connection/index.ts
apps/api/routes/oauth.ts
apps/api/services/connection_and_sync_service.ts
apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
apps/sync-worker/services/sync_service.ts
packages/core/lib/expand.ts
packages/core/mappers/account.ts
packages/core/mappers/connection.ts
packages/core/mappers/contact.ts
packages/core/mappers/event.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/capsule/index.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/index.ts
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/zendesk_sell/index.ts
packages/core/remotes/crm/zoho_crm/index.ts
packages/core/services/connection_service.ts
packages/core/types/crm/account.ts
packages/core/types/crm/contact.ts
packages/core/types/crm/event.ts
packages/core/types/crm/lead.ts
packages/core/types/crm/opportunity.ts
packages/types/connection.ts
packages/types/customer.ts
packages/types/webhook.ts

chore: more specific types for connections and creds

---

packages/core/services/common_models/account_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/event_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/sync-workflows/activities/populate_associations.ts

chore: logs for populateAssociations

---

apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/components/logs/HttpMethodSelect.tsx
openapi/mgmt/components/schemas/objects/webhook.yaml
openapi/mgmt/openapi.bundle.json
openapi/mgmt/paths/webhook.yaml
packages/core/lib/webhook.ts
packages/schemas/gen/mgmt.ts
packages/types/webhook.ts

chore: only support POST webhooks

---

apps/api/routes/internal/v1/index.ts
apps/api/routes/oauth.ts

fix: salesforce remote id

---

packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/utils/paginator.ts

chore: create paginator abstraction for simplicity

---

apps/api/routes/internal/v1/destination/index.ts
apps/api/routes/internal/v1/index.ts
packages/core/dependency_container.ts
packages/core/mappers/destination.ts
packages/core/services/destination_service.ts
packages/db/prisma/migrations/20230419173324_destination/migration.sql
packages/db/prisma/migrations/20230419175740_updated_at/migration.sql
packages/db/prisma/schema.prisma
packages/types/destination.ts
packages/types/index.ts

feat: destinations CRUD

---

packages/sync-workflows/activities/log_sync_finish.ts
packages/sync-workflows/workflows/run_sync.ts

- Convert logger obj to include context
- Make the error message fixed
- Add stack trace to logger line

chore: add original stack trace for failed syncs

---

packages/types/destination.ts

chore: postgres config

---

apps/api/index.ts
apps/api/services/application_service.ts

fix: return an 401 instead of a 404 on unknown api key

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
packages/types/destination.ts

ability to specify postgres schema

chore: add postgres schema

---

packages/core/remotes/crm/salesforce/index.ts

fix: poll every 10 seconds instead of 1 second to avoid eating up quota

---

packages/core/remotes/crm/hubspot/index.ts

fix: hubspot should be filtering on > archivedAt for archived records

---

apps/api/routes/crm/v1/lead.ts
openapi/crm/openapi.bundle.json
openapi/crm/openapi.yaml
openapi/crm/paths/leads@_search.yaml
packages/core/services/common_models/lead_service.ts
packages/schemas/crm.ts
packages/schemas/gen/crm.ts
packages/types/crm/lead.ts

feat: lead search by email

---

packages/core/remotes/crm/salesforce/index.ts

fix: only fetch available properties

---

packages/sync-workflows/activities/import_records.ts

For ease of debugging on temporal cloud

chore: more context in activity payload

---

apps/api/routes/internal/v1/webhook/index.ts
apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
apps/mgmt-ui/src/components/configuration/destination/S3DestinationDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/integration/IntegrationDetailsPanel.tsx
apps/mgmt-ui/src/components/customers/NewCustomer.tsx
apps/mgmt-ui/src/context/notification.tsx
apps/mgmt-ui/src/pages/_app.tsx
apps/mgmt-ui/src/pages/api/internal/webhook/delete.ts

Fixes: #722
Tested locally
https://www.loom.com/share/c184fb000f03484ea3eeb050d8667530

feat(mgmt-ui): Add notification when saving

---

helm/Chart.yaml
helm/templates/_helpers.tpl
helm/templates/schema-job.yaml

This ports over fixes from the supaglue/helm-charts repo to this one

fix: database url in helm chart

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
packages/core/services/destination_service.ts

Fix destination name update
Tested locally

fix: destination update name

---

apps/api/routes/internal/v1/webhook/index.ts
apps/mgmt-ui/src/components/configuration/IntegrationDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/components/customers/NewCustomer.tsx
apps/mgmt-ui/src/context/notification.tsx
apps/mgmt-ui/src/pages/_app.tsx
apps/mgmt-ui/src/pages/api/internal/webhook/delete.ts

This is a port of https://github.com/supaglue-labs/supaglue/pull/723 onto main

feat: notification bar

---

apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/layout/Navigator.tsx

fix: clean up webhook form

---

apps/api/routes/internal/v1/customer/connection/index.ts

chore: support connection post for salesforce

---

packages/core/mappers/account.ts
packages/core/mappers/contact.ts
packages/core/mappers/event.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/mappers/user.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/event_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/core/services/common_models/user_service.ts
packages/types/crm/account.ts
packages/types/crm/contact.ts
packages/types/crm/event.ts
packages/types/crm/lead.ts
packages/types/crm/opportunity.ts
packages/types/crm/user.ts

Reverts supaglue-labs/supaglue#770

chore: revert "feat: write raw_data into jsonb column"

---

packages/core/mappers/account.ts
packages/core/mappers/contact.ts
packages/core/mappers/event.ts
packages/core/mappers/lead.ts
packages/core/mappers/opportunity.ts
packages/core/mappers/user.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/services/common_models/account_service.ts
packages/core/services/common_models/contact_service.ts
packages/core/services/common_models/event_service.ts
packages/core/services/common_models/lead_service.ts
packages/core/services/common_models/opportunity_service.ts
packages/core/services/common_models/user_service.ts
packages/types/crm/account.ts
packages/types/crm/contact.ts
packages/types/crm/event.ts
packages/types/crm/lead.ts
packages/types/crm/opportunity.ts
packages/types/crm/user.ts

Reverts supaglue-labs/supaglue#771
This contains a fix to not fetch compound fields which is not allowed by the Bulk API.

chore: restore feat: write raw_data into jsonb column

---

apps/mgmt-ui/src/components/configuration/IntegrationDetailsPanel.tsx

Surface integration id in mgmt portal to developers to help with debugging

chore: for devxp, make integration id available for developers

---

apps/mgmt-ui/src/hooks/useNextLambdaEnv.ts
apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx

API_HOST could be empty during load; be consistent with other hooks for now

fix: data could be undefined during loading

---

packages/core/errors.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/salesforce/index.ts

chore: don't error, warn instead, on 429s

---

packages/db/prisma/schema.prisma

- the column name is now camelCased in prisma, so map

fix: snakecase map for new flag

---

apps/api/routes/engagement/v1/contact.ts
openapi/engagement/components/schemas/objects/contact.yaml
openapi/engagement/components/schemas/objects/email_addresses.yaml
openapi/engagement/components/schemas/objects/phone_numbers.yaml
openapi/engagement/openapi.bundle.json
packages/core/mappers/engagement/address.ts
packages/core/mappers/engagement/contact.ts
packages/core/mappers/engagement/email_address.ts
packages/core/mappers/engagement/index.ts
packages/core/mappers/engagement/phone_number.ts
packages/core/remotes/engagement/outreach/mappers.ts
packages/core/services/common_models/engagement/contact_service.ts
packages/schemas/gen/engagement.ts
packages/types/engagement/common/email_address.ts
packages/types/engagement/common/phone_number.ts
packages/types/engagement/index.ts

Support reading engagement contacts for outreach
Tested locally

feat: reading engagement contacts

---

apps/api/routes/engagement/v1/index.ts
apps/api/routes/engagement/v1/sequence.ts
apps/sync-worker/dependency_container.ts
openapi/engagement/components/schemas/objects/sequence.yaml
openapi/engagement/openapi.bundle.json
packages/core/dependency_container.ts
packages/core/mappers/engagement/index.ts
packages/core/mappers/engagement/sequence.ts
packages/core/remotes/engagement/outreach/index.ts
packages/core/remotes/engagement/outreach/mappers.ts
packages/core/services/common_models/engagement/index.ts
packages/core/services/common_models/engagement/sequence_service.ts
packages/db/index.ts
packages/db/prisma/migrations/20230509233041_engagement_sequence_tags/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/engagement.ts
packages/schemas/gen/engagement.ts
packages/sync-workflows/activities/import_records.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/workflows/run_sync.ts
packages/types/engagement/index.ts
packages/types/engagement/sequence.ts

Support syncing and fetching sequences
Tested locally

feat: support syncing and fetching sequences

---

apps/api/routes/crm/v1/account.ts
openapi/crm/openapi.bundle.json
openapi/crm/paths/accounts@_search.yaml
openapi/crm/paths/contacts@_search.yaml
openapi/crm/paths/leads@_search.yaml
openapi/crm/paths/opportunities@_search.yaml
packages/core/services/common_models/crm/account_service.ts
packages/core/services/common_models/crm/contact_service.ts
packages/core/services/common_models/crm/lead_service.ts
packages/core/services/common_models/crm/opportunity_service.ts
packages/schemas/gen/crm.ts
packages/types/crm/account.ts
packages/types/crm/contact.ts
packages/types/crm/lead.ts
packages/types/crm/opportunity.ts

feat: add remote_id as a _search filter

---

apps/api/routes/engagement/v1/contact.ts
packages/core/lib/index.ts
packages/core/lib/util.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/engagement/outreach/index.ts
packages/core/remotes/engagement/outreach/mappers.ts

feat: support updating contacts in outreach

---

apps/api/routes/internal/v1/customer/connection/index.ts
openapi/versioned/version-0.8.1/crm/openapi.bundle.json
openapi/versioned/version-0.8.1/engagement/openapi.bundle.json
openapi/versioned/version-0.8.1/mgmt/openapi.bundle.json
packages/core/services/connection_service.ts

We need to do this for people to be able to migrate from self-hosted to Cloud

feat: list unsafe connections

---

apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
packages/core/services/webhook_service.ts

chore: disable svix temporarily to make self-hosted upgrade easier

---

.husky/pre-commit
apps/api/middleware/api_key.ts
apps/api/middleware/connection.ts
apps/api/middleware/internal_application.ts
package.json
packages/core/lib/logger.ts
yarn.lock

fix: add more context to logs, and add context when we have it - not later

---

packages/core/remotes/crm/hubspot/index.ts

This reverts commit 6434512c88c1d58b6cede053d074c63167de8850.
We're running into hubspot URI length issues because we're fetching too many properties with raw data. Later, we will bring this feature back with fix.

fix: Revert "feat: fetch all hubspot properties (#776)"

---

apps/api/routes/internal/v1/destination/index.ts
apps/api/routes/internal/v1/index.ts
packages/core/dependency_container.ts
packages/core/mappers/destination.ts
packages/core/services/destination_service.ts
packages/db/prisma/migrations/20230518201140_destination/migration.sql
packages/db/prisma/schema.prisma
packages/types/destination.ts
packages/types/index.ts

Cherry-picked:
- https://github.com/supaglue-labs/supaglue/commit/9499467bd0e6effb819d4f261ce0e356198a1e1f
- https://github.com/supaglue-labs/supaglue/commit/9c2c6cef881f2263e2da737d07fdd876144027ff

chore: add destinations CRUD

---

packages/core/services/common_models/crm/account_service.ts
packages/core/services/common_models/crm/contact_service.ts
packages/core/services/common_models/crm/lead_service.ts
packages/core/services/common_models/crm/opportunity_service.ts

Hubspot occasionally dedups contacts by email and accounts by domain. This can lead to behavior where calling `GET` on a remoteId actually yields a record with a different remoteId (the one that it got merged into).
In this case, we update both records in our cache.
Tested in prod.

fix: handle hubspot dedups

---

packages/core/remotes/crm/index.ts
packages/core/remotes/engagement/index.ts

chore: warn instead of error for remote client error to reduce noise

---

.github/workflows/docker_build_and_push.yml

This is preventing staging deploys

ci: request correct permissions for aws OIDC

---

apps/salesforce-pub-sub/index.ts

Fixes pub sub subscription issue

fix: get instanceurl from token in pub sub

---

packages/db/prisma/migrations/20230519210809_integration_destination/migration.sql
packages/db/prisma/schema.prisma

chore: destination_id on integration in prisma.schema

---

docs/docs/roadmap.md
docs/versioned_docs/version-0.8.7/roadmap.md

docs: update roadmap to point to github

---

packages/db/prisma/migrations/20230524190106_sync_version/migration.sql
packages/db/prisma/schema.prisma

chore: sync version for migration

---

apps/api/index.ts
apps/api/services/connection_and_sync_service.ts
apps/sync-worker/services/sync_service.ts

also, run `processSyncChanges` every 10s instead of every 60s

chore: handle v1 and v2 syncs in processSyncChanges

---

apps/api/index.ts
apps/api/routes/internal/v1/customer/connection/index.ts
apps/api/routes/mgmt/v1/customer/connection/index.ts
apps/api/routes/oauth.ts
apps/api/services/connection_and_sync_service.ts
apps/sync-worker/services/sync_service.ts

chore: allow creating connection with specific sync version

---

apps/api/routes/mgmt/v1/index.ts
apps/api/routes/mgmt/v1/sync_migration.ts
openapi/mgmt/openapi.bundle.json
openapi/mgmt/openapi.yaml
openapi/mgmt/paths/sync_migration_get_connections.yaml
openapi/mgmt/paths/sync_migration_migrate_connection.yaml
packages/schemas/gen/mgmt.ts

chore: public endpoints to migrate connections from v1 to v2

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
apps/mgmt-ui/src/components/configuration/destination/S3DestinationDetailsPanel.tsx
packages/core/destination_writers/base.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/destination_writers/util.ts
packages/core/package.json
packages/core/services/destination_service.ts
packages/sync-workflows/activities/sync_records_to_destination.ts
yarn.lock

Tested locally, and it works. But need to fix forcing full refresh for S3 destinations

feat: support s3 destination

---

apps/api/routes/internal/v1/index.ts
apps/api/routes/mgmt/v1/sync_migration.ts

chore: internal endpoint for sync migration

---

packages/core/remotes/crm/hubspot/index.ts

fix: create/update/delete properties, return fields that were created for custom objects

---

packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/keys/crm/account.ts
packages/core/keys/crm/contact.ts
packages/core/keys/crm/lead.ts
packages/core/keys/crm/opportunity.ts
packages/core/keys/crm/user.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/engagement/outreach/index.ts
packages/core/services/common_models/base_service.ts
packages/types/crm/base.ts

feat: write _supaglue_emitted_at to destination

---

scripts/release.sh

fix: fix release script

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
apps/mgmt-ui/src/components/configuration/destination/S3DestinationDetailsPanel.tsx

- if there is a destination object, always set its field in react state

fix(mgmt-ui): updating destinations

---

docs/docs/integration-patterns/managed-syncs.md
docs/docs/quickstart.mdx
docs/versioned_docs/version-0.9.3/getting-started.mdx
docs/versioned_docs/version-0.9.4/quickstart.mdx
packages/core/services/destination_service.ts

- require name to be set for destination create/update
- `setup` -> `set up` when used as verb

chore: require name for destination create/update

---

packages/core/remotes/crm/base.ts
packages/core/remotes/crm/capsule/index.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/salesforce/mappers.ts
packages/core/remotes/crm/zendesk_sell/index.ts
packages/core/remotes/crm/zoho_crm/index.ts
packages/core/remotes/engagement/base.ts
packages/core/remotes/engagement/outreach/index.ts
packages/core/services/common_models/crm/account_service.ts
packages/core/services/common_models/crm/common_model_service.ts
packages/core/services/common_models/crm/contact_service.ts
packages/core/services/common_models/crm/lead_service.ts
packages/core/services/common_models/crm/opportunity_service.ts
packages/core/services/common_models/engagement/common_model_service.ts
packages/sync-workflows/activities/import_records.ts
packages/sync-workflows/activities/sync_records_to_destination.ts

chore: add CRM salesforce methods for listing raw objects

---

packages/core/services/common_models/crm/account_service.ts
packages/core/services/common_models/crm/contact_service.ts
packages/core/services/common_models/crm/lead_service.ts
packages/core/services/common_models/crm/opportunity_service.ts

fix: don't update id on hubspot duplicates

---

docker-compose.override.dev.yml
docker-compose.yml

We need to wait until temporal server is up before we can add attributes

fix: do not add attributes until temporal server is up

---

apps/mgmt-ui/src/pages/api/index.ts

fix(mgmt-ui): fix a truthy issue when using auth.js locally

---

packages/core/destination_writers/base.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/lib/ratelimit.ts
packages/core/remotes/base.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/services/common_models/crm/common_model_service.ts
packages/core/services/common_models/engagement/common_model_service.ts
packages/sync-workflows/activities/sync_records_to_destination.ts

Still need to:
- Pull associations for objects
- Pull out some fields that will be necessary to write into postgres not into the JSONB column (need to define type/interface to pull out id, last_modified_at, etc.)

chore: partial work for syncing records from hubspot

---

packages/core/destination_writers/s3.ts

fix: s3 destination using wrong key

---

.gitignore
apps/mgmt-ui/.env.build
scripts/build_and_push.sh

- use a clean .env when building

fix(build): use a .env from a template for building mgmt-ui

---

packages/core/remotes/crm/salesforce/index.ts

fix: add empty callback for pipeline

---

packages/core/destination_writers/base.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/sync-workflows/lib/analytics.ts
packages/types/index.ts
packages/types/raw_record.ts

chore: associations for hubspot and temporal activity to write raw records

---

packages/core/services/common_models/base_service.ts

fix: v1 syncs should pull record not object

---

packages/core/destination_writers/postgres.ts

- remove caching for now since pg pool cache isn't invalidated right now. some customers run into this issue

fix(core): remove postgres pool cache

---

scripts/build_and_push.sh

fix(ci): fix .env cleanup

---

apps/mgmt-ui/src/components/configuration/ApiKeyTabPanel.tsx
apps/mgmt-ui/src/components/configuration/DeleteApiKey.tsx
apps/mgmt-ui/src/components/configuration/DeleteWebhook.tsx
apps/mgmt-ui/src/components/configuration/RegenerateApiKey.tsx
apps/mgmt-ui/src/components/configuration/RevokeApiKey.tsx
apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/components/configuration/integration/IntegrationDetailsPanel.tsx
apps/mgmt-ui/src/components/connections/DeleteConnection.tsx
apps/mgmt-ui/src/components/customers/DeleteCustomer.tsx

- revoke api key
- regenerate api key
- delete webhook
- show character fill for existing api key

fix(mgmt-ui): add confirmation dialogs for destructive ops

---

apps/api/routes/internal/sync_config/index.ts
apps/api/routes/internal/sync_history.ts
apps/api/routes/mgmt/v1/sync_history.ts
apps/api/routes/mgmt/v2/sync_config/index.ts
apps/mgmt-ui/src/components/logs/LogsTable.tsx
openapi/v2/mgmt/components/schemas/sync_history.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/core/mappers/sync_history.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/services/sync_config_service.ts
packages/core/services/sync_history_service.ts
packages/db/prisma/migrations/20230615182748_sync_history/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/gen/v2/mgmt.ts
packages/sync-workflows/activities/get_destination.ts
packages/sync-workflows/activities/get_sync_config_by_sync_id.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/log_sync_start.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts
packages/sync-workflows/workflows/run_managed_sync.ts
packages/sync-workflows/workflows/run_sync.ts
packages/types/sync.ts
packages/types/sync_config.ts
packages/types/sync_history.ts
packages/types/webhook.ts

chore: support SyncConfig in V2 syncs

---

docs/docs/quickstart.mdx

docs: fix quickstart destination select

---

apps/api/routes/internal/sync_config/index.ts
apps/api/routes/mgmt/v2/sync_config/index.ts
openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/services/sync_config_service.ts
packages/schemas/gen/v2/mgmt.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/sync-workflows/activities/sync_records_to_destination.ts
packages/sync-workflows/workflows/run_managed_sync.ts
packages/types/sync_config.ts

feat: sync hubspot custom object without associations

---

docs/docs/connectors/ms_dynamics_365_sales.md
packages/core/package.json
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
yarn.lock

feat: support raw objects for Dynamics 365 syncs

---

apps/api/routes/mgmt/v2/sync_config/index.ts
openapi/v2/mgmt/components/schemas/create_update_destination.yaml
openapi/v2/mgmt/components/schemas/create_update_provider.yaml
openapi/v2/mgmt/components/schemas/objects/destination.yaml
openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
openapi/v2/mgmt/openapi.bundle.json
openapi/v2/mgmt/paths/sync_configs.yaml
openapi/v2/mgmt/paths/sync_configs@{sync_config_id}.yaml
packages/schemas/gen/v2/mgmt.ts

chore: clean up openAPI schema

---

apps/api/routes/internal/sync_config/index.ts
apps/api/routes/mgmt/v2/sync_config/index.ts
openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
openapi/v2/mgmt/openapi.bundle.json
openapi/v2/mgmt/paths/sync_configs.yaml
openapi/v2/mgmt/paths/sync_configs@{sync_config_id}.yaml
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/capsule/index.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/zendesk_sell/index.ts
packages/core/remotes/crm/zoho_crm/index.ts
packages/core/remotes/engagement/base.ts
packages/core/remotes/engagement/outreach/index.ts
packages/core/services/common_models/crm/account_service.ts
packages/core/services/common_models/crm/common_model_service.ts
packages/core/services/common_models/crm/contact_service.ts
packages/core/services/common_models/crm/custom_object_service.ts
packages/core/services/common_models/crm/lead_service.ts
packages/core/services/common_models/crm/opportunity_service.ts
packages/core/services/common_models/engagement/common_model_service.ts
packages/core/services/sync_config_service.ts
packages/schemas/gen/v2/mgmt.ts
packages/sync-workflows/activities/import_records.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/sync-workflows/activities/sync_records_to_destination.ts

chore: rename raw{Standard|Custom}Objects -> {standard|custom}Objects

---

apps/mgmt-ui/package.json
apps/mgmt-ui/src/middleware.ts
yarn.lock

- black box upgrade to see the impact on 307 and perf. to test in staging

chore(mgmt-ui): upgrade clerk and its middleware

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/core/mappers/sync_config.ts
packages/db/prisma/migrations/20230620231839_sync_paused/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/gen/v2/mgmt.ts
packages/types/sync.ts
packages/types/sync_config.ts

chore: add schema and field mappings for SyncConfig and Sync

---

apps/mgmt-ui/src/components/AccountMenu/index.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/configuration/[...tab].tsx

- allow users to manually navigate to cdc webhooks
- show the tab for select users
- show mui avatar instead of letter "m"

chore(mgmt-ui): profile avatar. gate cdc

---

packages/core/remotes/crm/salesforce/index.ts

chore: add NOT_FOUND to sfdc 404 error map

---

apps/mgmt-ui/src/components/configuration/CDCWebhookTabPanel.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/configuration/[...tab].tsx

chore(mgmt): cdc beta signup

---

packages/core/remotes/crm/hubspot/index.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts

if we map
col_1 -> colA
col_2 -> colA
the previous code had a bug

fix: fix bug with duplicate fields on mapped side

---

apps/api/routes/internal/sync_config/index.ts
apps/api/routes/mgmt/v2/sync_config/index.ts
apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/hooks/useSyncConfig.ts
apps/mgmt-ui/src/hooks/useSyncConfigs.ts
packages/core/destination_writers/base.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/lib/schema.ts
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/services/sync_config_service.ts
packages/db/prisma/schema.prisma
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/sync-workflows/workflows/run_managed_sync.ts
packages/types/sync.ts
packages/types/sync_config.ts

chore: rename rawObjects -> standardObjects, rawCustomObjects -> customObjects

---

apps/mgmt-ui/src/hooks/useConnections.ts

- fix connections not showing up if chars are not uri encoded

fix(mgmt-ui): encode external customer id when fetching connection

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
apps/mgmt-ui/src/components/configuration/destination/S3DestinationDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
packages/core/services/destination_service.ts
packages/types/destination.ts

Addresses SUP1-363 and SUPG1-376
Fix destination UI/UX:
- disable test/save until form is dirty
- handle testing existing destinations
- Navigate back on successful sync config save
https://www.loom.com/share/8b0d577b96114080bcebe147951e2d6c
https://www.loom.com/share/501edbb785e4403c8b9390ac8306686e

fix(mgmt-ui): Fix destination UI UX

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx
apps/mgmt-ui/src/components/logs/LogsTable.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/configuration/[...tab].tsx

chore: mgmt-ui terminology fixes

---

apps/mgmt-ui/src/components/logs/LogsTable.tsx
openapi/v2/mgmt/components/schemas/sync_history.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/core/mappers/sync_history.ts
packages/core/services/sync_history_service.ts
packages/db/prisma/migrations/20230622212732_sync_history_object/migration.sql
packages/db/prisma/schema.prisma
packages/schemas/gen/v2/mgmt.ts
packages/sync-workflows/activities/log_sync_start.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts
packages/sync-workflows/workflows/run_managed_sync.ts
packages/types/sync_history.ts
packages/types/webhook.ts

chore: rawObject -> standardObject, customObject for sync history

---

apps/api/Dockerfile
apps/mgmt-ui/Dockerfile
apps/salesforce-pub-sub/Dockerfile
apps/salesforce-pub-sub/package.json
apps/sync-worker/Dockerfile
apps/sync-worker/package.json
docker-compose.override.dev.yml
packages/core/package.json
packages/db/prisma/schema.prisma
yarn.lock

Also fixes the pub sub worker image dependency issues.
Tested locally

fix: pin to bullseye for images, other fixes

---

openapi/v2/crm/components/schemas/objects/object_type.yaml
openapi/v2/crm/openapi.bundle.json
packages/core/destination_writers/base.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/hubspot/mappers.ts
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/schemas/gen/v2/crm.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/types/crm/association_type.ts

chore: RawStandardObject -> StandardObject

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx

fix: make links look like links

---

apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/pages/applications/[applicationId]/customers/index.tsx

fix: encode other call sites to customer id

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx

chore: disable standard and custom if not supported

---

apps/mgmt-ui/src/pages/applications/[applicationId]/configuration/[...tab].tsx

fix: fix configuration tabs

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx

there is also a cache issue that isn't addressed in this PR

fix: custom objects saving into standard objects

---

docs/docs/integration-patterns/actions-api.md
docs/docs/platform/api-authentication.md

docs: reference v2 instead of v1

---

docs/docs/connectors/hubspot.md
docs/docs/connectors/ms_dynamics_365_sales.md
docs/docs/connectors/pipedrive.md
docs/docs/connectors/salesforce.md
docs/docs/destinations/postgres.md
docs/docs/destinations/s3.md
docs/docs/integration-patterns/actions-api.md
docs/docs/platform/api-authentication.md

docs: sync object support matrix

---

docs/docs/integration-patterns/managed-syncs.md

docs: update docs for managed sync

---

README.md

docs: Update README.md with new video

---

docs/docs/destinations/postgres.md
docs/docs/destinations/s3.md
docs/docs/quickstart.mdx

docs: add schema evolution note

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx

Make plus button always visible.
https://www.loom.com/share/a25713285c1e4159bf2c1e8c6dda10fd

fix: responsive sync configs ui

---

docs/docusaurus.config.js
openapi/v2/mgmt/openapi.bundle.json
openapi/v2/mgmt/openapi.yaml
openapi/v2/mgmt/paths/force_sync.yaml
openapi/v2/mgmt/paths/sync_history.yaml
openapi/v2/mgmt/paths/sync_info.yaml
openapi/v2/mgmt/paths/webhook.yaml
openapi/v2/mgmt/webhooks/webhook.yaml

docs: re-order tags

---

apps/api/services/connection_and_sync_service.ts
apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
docs/docs/integration-patterns/managed-syncs.md
openapi/v2/mgmt/components/schemas/objects/sync_config_data.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/schemas/gen/v2/mgmt.ts
packages/types/sync_config.ts

chore: rename enableSyncOnConnectionCreation -> startSyncOnConnectionCreation for clarity

---

packages/core/destination_writers/postgres.ts

This was deployed as hotfix but never merged into main.
Fixes: #### 

fix: V0.11.0 hotfix2 (#1108)

---

packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/ms_dynamics_365_sales/mappers.ts

Tested locally against the trial dynamics instance

feat: actions api for MS Dynamics 365

---

packages/core/destination_writers/postgres.ts
packages/core/remotes/crm/salesforce/index.ts

if there are 2 records, pick the one with the larger last_modified_at

fix: dedupe records written to postgres by last_modified_at

---

.github/workflows/docker_build_and_push.yml
docker-compose.yml

fix: pin the version of the prisma cli we use with npx

---

packages/core/destination_writers/postgres.ts

fix: make all postgres table names lowercase

---

packages/db/prisma/migrations/20230627202821_object/migration.sql
packages/db/prisma/schema.prisma

chore: change to objectType and object in DB

---

docs/docs/destinations/postgres.md
docs/docs/integration-patterns/managed-syncs.md

docs: add query patterns

---

docs/docs/api.md
docs/docs/destinations/postgres.md
docs/docs/integration-patterns/actions-api.md
docs/docs/integration-patterns/managed-syncs.md
docs/docs/integration-patterns/real-time-events.md
docs/docs/platform/common-object.md
openapi/v2/crm/openapi.bundle.json
openapi/v2/crm/openapi.yaml
openapi/v2/engagement/openapi.bundle.json
openapi/v2/engagement/openapi.yaml

- Add reference to read pattern in action api references
- Convert common schema to common object
- Associate integration patterns with reads and writes

docs: some cleanup

---

packages/db/prisma/migrations/20230628024231_remove_connection_unique_on_object_syncs/migration.sql
packages/db/prisma/schema.prisma

fix: remove uniqueness constraint on connection for object_syncs

---

apps/api/services/connection_and_sync_service.ts
apps/sync-worker/dependency_container.ts
packages/core/dependency_container.ts
packages/core/mappers/object_sync_run.ts
packages/core/services/destination_service.ts
packages/core/services/object_sync_run_service.ts
packages/core/types/object_sync_run.ts
packages/sync-workflows/activities/get_object_sync.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/log_object_sync_finish.ts
packages/sync-workflows/activities/log_object_sync_start.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts
packages/sync-workflows/activities/sync_records.ts
packages/sync-workflows/activities/update_object_sync_state.ts
packages/sync-workflows/services/sync_service.ts
packages/sync-workflows/workflows/index.ts
packages/sync-workflows/workflows/run_managed_sync.ts
packages/sync-workflows/workflows/run_object_sync.ts
packages/types/object_sync.ts
packages/types/object_sync_run.ts
packages/types/webhook.ts

This implements object syncs (one Temporal schedule per object).
This is implemented parallel to the existing system, and is not active. The next PR will include code to migrate to the new system, etc.

chore: implement object syncs

---

openapi/v2/mgmt/openapi.bundle.json
openapi/v2/mgmt/openapi.yaml
openapi/v2/mgmt/paths/connections@{connection_id}.yaml

fix: openapi tags

---

openapi/v2/mgmt/components/schemas/webhook-payload.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/schemas/gen/v2/mgmt.ts

chore: update openapi webhook payload spec

---

apps/api/routes/crm/v2/account.ts
apps/api/routes/crm/v2/contact.ts
apps/api/routes/crm/v2/lead.ts
apps/api/routes/crm/v2/opportunity.ts
apps/api/routes/crm/v2/user.ts
packages/core/dependency_container.ts
packages/core/mappers/provider.ts
packages/core/remotes/crm/base.ts
packages/core/remotes/crm/capsule/index.ts
packages/core/remotes/crm/hubspot/index.ts
packages/core/remotes/crm/ms_dynamics_365_sales/index.ts
packages/core/remotes/crm/pipedrive/index.ts
packages/core/remotes/crm/salesforce/index.ts
packages/core/remotes/crm/zendesk_sell/index.ts
packages/core/remotes/crm/zoho_crm/index.ts
packages/core/services/common_models/crm/common_model_service.ts

- Apply the object schema (if given) to the actions API
Tested locally

fix: apply schema to actions api

---

apps/api/routes/mgmt/v2/sync_run.ts
openapi/v2/mgmt/components/schemas/sync_run.yaml
openapi/v2/mgmt/openapi.bundle.json
packages/schemas/gen/v2/mgmt.ts
packages/sync-workflows/services/sync_service.ts

Currently we are early-exiting on some errs even though we call multiple Temporal APIs sequentially. We want to get through all the steps. We don't want to stop on the first failure.

fix: small fix for processSyncChanges

---

packages/core/mappers/provider.ts
packages/core/services/common_models/crm/common_model_service.ts
packages/core/services/provider_service.ts
packages/sync-workflows/activities/sync_raw_records_to_destination.ts
packages/sync-workflows/activities/sync_records.ts
packages/sync-workflows/activities/sync_records_to_destination.ts

chore: ProviderService generics

---

packages/core/destination_writers/postgres.ts
packages/sync-workflows/workflows/run_object_sync.ts

chore: reduce heartbeat timeout

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx

Fixes SUP1-417.
https://www.loom.com/share/151a357c4ea14b998aeb33a15e090f4f

fix(mgmt-ui): multi-combobox should autoselect on blur

---

apps/mgmt-ui/src/components/configuration/destination/PostgresDestinationDetailsPane.tsx
apps/mgmt-ui/src/components/configuration/destination/S3DestinationDetailsPanel.tsx

Fixes SUP1-409
Tested locally
https://www.loom.com/share/a9a44968bfe54639b9a55d01959b45b3

fix: separate test and save buttons

---

packages/core/destination_writers/postgres.ts

fix: null char for other call site

---

docs/docs/quickstart.mdx

fix: quicktstart

---

packages/core/services/provider_service.ts

fix: upsert object to syncconfig

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx
apps/mgmt-ui/src/pages/_app.tsx

Fixes: SUP1-408
Tested locally
https://www.loom.com/share/600c9beb61b04fe5bae89d17053c61cf

feat: copy application ID

---

apps/api/init_scripts/init_temporal.ts

fix: temporal search attributes init script

---

packages/core/remotes/impl/pipedrive/index.ts
packages/core/remotes/impl/pipedrive/mappers.ts
packages/core/remotes/impl/pipedrive/types.ts

feat: rewrite custom field keys & values in both directions for pipedrive

---

apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/components/SwitchWithLabel/index.tsx
apps/mgmt-ui/src/components/configuration/WebhookTabPanel.tsx
apps/mgmt-ui/src/components/configuration/schema/DeleteSchema.tsx
apps/mgmt-ui/src/components/configuration/schema/DeleteSchemaButton.tsx
apps/mgmt-ui/src/components/configuration/schema/SchemaDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/schema/SchemaListPanel.tsx
apps/mgmt-ui/src/components/configuration/schema/SchemaTabPanelContainer.tsx
apps/mgmt-ui/src/hooks/useSchemas.ts
apps/mgmt-ui/src/hooks/useSyncConfig.ts
apps/mgmt-ui/src/pages/api/internal/schemas/[...schemaId].ts
apps/mgmt-ui/src/pages/api/internal/schemas/create.ts
apps/mgmt-ui/src/pages/api/internal/schemas/index.ts
apps/mgmt-ui/src/pages/api/internal/schemas/update.ts
apps/mgmt-ui/src/pages/applications/[applicationId]/configuration/[...tab].tsx

Schemas tab list view + create/update
tested locally
https://www.loom.com/share/c219fe294e2049ffb10cac289ee03460

feat(mgmt-ui): Schemas tab

---

apps/mgmt-ui/src/components/configuration/provider/ProviderDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/schema/SchemaDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/utils/provider.ts

- TODO: Implement some way to add inline schema
https://www.loom.com/share/4a4c0c534b49480fba79ce5e3d6a62e4

feat: object to schema mapping on provider

---

docs/docs/integration-patterns/actions-api.md
docs/docs/integration-patterns/managed-syncs.md
docs/docs/platform/common-schema.md
docs/versioned_docs/version-0.12.2/integration-patterns/actions-api.md
docs/versioned_docs/version-0.12.2/integration-patterns/managed-syncs.md
docs/versioned_docs/version-0.12.2/platform/common-schema.md

docs: fix common schema reference

---

apps/mgmt-ui/src/components/configuration/provider/ProviderDetailsPanel.tsx
apps/mgmt-ui/src/components/configuration/schema/SchemaDetailsPanel.tsx

fix: mgmt-ui

---

packages/core/dependency_container.ts
packages/core/services/common_objects/crm/common_object_service.ts
packages/core/services/connection_service.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/activities/sync_records.ts

Apply schema to actions API request payloads
Testing locally

feat: support schema mappings on actions API (crm only)

---

packages/core/services/object_sync_run_service.ts

- remove vector for consuming incorrectly

chore: simplify consuming sync run

---

apps/api/routes/oauth.ts

`Can't find customer with id: test-customer-id. Ensure it is URI encoded if needed.`
`Can't find provider with name: hubspot.`

chore: improve oauth error messages

---

packages/core/lib/schema.ts

later we'll allow developer to specify required fields that MUST be mapped by customers

chore: make schema fields optional by default

---

apps/mgmt-ui/src/components/ApplicationMenu/index.tsx

fix(mgmt-ui): Close menu when switching applications

---

apps/api/routes/mgmt/v2/field_mapping/index.ts

fix: return out

---

packages/core/remotes/impl/pipedrive/index.ts

fix: fix pipedrive custom fields

---

docs/docs/platform/custom-objects.md

docs: custom objects API

---

packages/core/destination_writers/postgres.ts

fix: fix null byte issue

---

docs/docs/integration-patterns/managed-syncs.md
docs/docs/platform/custom-objects.md

docs: improve custom objects docs

---

apps/api/dependency_container.ts
apps/api/routes/internal/index.ts
apps/api/routes/internal/system/index.ts
apps/api/services/connection_and_sync_service.ts
apps/sync-worker/dependency_container.ts
packages/core/dependency_container.ts
packages/core/services/system_settings_service.ts
packages/db/prisma/migrations/20230711221103_process_sync_changes_list/migration.sql
packages/db/prisma/schema.prisma
packages/sync-workflows/activities/do_process_sync_changes.ts
packages/sync-workflows/activities/index.ts
packages/sync-workflows/services/sync_service.ts
packages/sync-workflows/workflows/process_sync_changes.ts
packages/types/system_settings.ts

this allows manual trigger of full refresh of processSyncChanges, which will help to backfill search attributes (among other things)

chore: manual trigger of processSyncChanges to backfill search attributes

---

apps/mgmt-ui/src/utils/provider.ts
packages/core/remotes/impl/gong/mappers.ts
packages/utils/constants.ts

chore: standard object selection for gong

---

packages/core/services/connection_service.ts

- add/merge based on object name

fix: updating object field mapping config

---

apps/api/services/connection_and_sync_service.ts
apps/mgmt-ui/src/components/logs/SyncsTable.tsx
apps/mgmt-ui/src/pages/api/internal/syncs/_trigger.ts

no that pretty but works for now.
later, we probably want to show this on the Sync Runs page also.
Also, we shouldn't show the button if a sync is already running, for better UX.

feat: allow trigger of sync on mgmt-ui

---

apps/mgmt-ui/src/pages/applications/[applicationId]/customers/index.tsx

Don't make developer replace `{{REPLACE_ME}}` and allow them to select from a dropdown of providers instead.
https://www.loom.com/share/dcf3f8d9e1eb45098510f1a61ddbf90d

feat: embed link dropdown

---

docs/docs/connectors/outreach.md

we don't support accounts and emails

docs: fix outreach supported common objects

---

packages/core/services/provider_service.ts

chore: enforce at most one object per schema for one provider

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
packages/core/destination_writers/mongodb.ts
packages/core/mappers/destination.ts

Ran into a few issues that weren't noticed before during previous runthroughs.
Tested locally against mongodb atlas

fix: issues when doing mongo runthrough

---

packages/core/remotes/impl/hubspot/index.ts

fix: fix syncing of associated line items when syncing hubspot deals

---

packages/db/prisma/migrations/20230719210847_entity/migration.sql
packages/db/prisma/schema.prisma

chore: entity stuff in DB

---

packages/db/prisma/migrations/20230719224319_entity_mappings/migration.sql
packages/db/prisma/schema.prisma

chore: entityMappings on provider

---

packages/db/prisma/migrations/20230719224753_connection_entity_mappings/migration.sql
packages/db/prisma/schema.prisma

chore: entityMappings on Connection db model

---

apps/mgmt-ui/src/components/configuration/schema/SchemaDetailsPanel.tsx

https://www.loom.com/share/705b6f7b11b64f8490a28720d8518a64

chore: add tooltip for field mappings

---

packages/core/destination_writers/mongodb.ts

Tested locally against mongodb atlas and hubspot/salesforce

feat: for mongodb, normalize fields

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigListPanel.tsx

feat: show entities on mgmt-ui for SyncConfig

---

apps/api/routes/mgmt/v2/entity_mapping/index.ts

fix: duplicate entity mappings

---

apps/mgmt-ui/src/pages/api/internal/properties/index.ts

fix: fetching properties

---

packages/core/remotes/impl/apollo/mapper.ts

fix: apollo sequence state sync

---

apps/mgmt-ui/src/pages/applications/[applicationId]/customers/[customerId]/connections/[providerName]/index.tsx

feat: show machine names on dropdown

---

packages/core/services/entity_service.ts
packages/types/entity.ts

chore: do not allow dashes in entity names

---

packages/core/destination_writers/mongodb.ts
packages/core/remotes/impl/gong/index.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/core/remotes/impl/salesforce/index.ts
packages/types/object_record.ts

chore: change _supaglue_mapped_data to only contain properties

---

apps/mgmt-ui/src/components/configuration/entity/EntityDetailsPanel.tsx

chore: FE validation for entity name

---

apps/mgmt-ui/src/components/configuration/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/utils/provider.ts
docs/docs/providers/intercom.md
packages/core/remotes/impl/intercom/index.ts
packages/core/remotes/impl/intercom/mappers.ts
packages/utils/constants.ts

feat: intercom standard object syncs

---

packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/mongodb.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/remotes/base.ts
packages/core/remotes/categories/crm/base.ts
packages/core/remotes/impl/gong/index.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/intercom/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/core/remotes/impl/salesforce/index.ts
packages/sync-workflows/activities/sync_entity_records.ts
packages/sync-workflows/activities/sync_object_records.ts
packages/types/fields_to_fetch.ts
packages/types/object_record.ts

chore: do field mapping in sync, not in each provider

---

docs/docs/tutorials/mongo-view-prisma-view.md

docs: mongo view tutorial

---

packages/core/destination_writers/base.ts
packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/mongodb.ts
packages/core/destination_writers/postgres.ts
packages/core/destination_writers/s3.ts
packages/core/remotes/base.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/salesforce/index.ts
packages/core/services/object_record_service.ts
packages/types/object_record.ts

feat: standard object cache invalidation

---

packages/core/remotes/impl/hubspot/mappers.ts

fix: wrong mapping for deal closed won

---

docs/docs/integration-patterns/actions-api.md

docs: add missing import

---

apps/mgmt-ui/src/hooks/useApplications.ts

I left staging open in a tab with the console/network panel open and tracked this down from that.

fix: client-side exception on returning to open tab/window

---

packages/core/remotes/impl/gong/index.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/intercom/index.ts
packages/core/remotes/impl/linear/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/types/object_record.ts

fix: use mappedProperties everywhere and enforce with type

---

packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/postgres.ts
packages/core/remotes/impl/ms_dynamics_365_sales/mappers.ts

- remove trunc after we migrate customer tables

fix: convert opportunity.amount (common schema) to float

---

apps/mgmt-ui/src/pages/applications/[applicationId]/customers/[customerId]/connections/[providerName]/index.tsx

chore: remove comment

---

docs/docs/destinations/bigquery.md
docs/docs/destinations/mysql.md
docs/docs/destinations/postgres.md
docs/docs/destinations/snowflake.md
docs/versioned_docs/version-0.13.3/destinations/bigquery.md
docs/versioned_docs/version-0.13.3/destinations/mysql.md
docs/versioned_docs/version-0.13.3/destinations/postgres.md
docs/versioned_docs/version-0.13.3/destinations/snowflake.md
docs/versioned_docs/version-0.13.4/destinations/bigquery.md
docs/versioned_docs/version-0.13.4/destinations/mysql.md
docs/versioned_docs/version-0.13.4/destinations/postgres.md
docs/versioned_docs/version-0.13.4/destinations/snowflake.md

docs: fix docs broken links

---

apps/mgmt-ui/src/pages/create-organization/[[...index]].tsx

fix: merge conflict

---

docs/docs/platform/common-schema/overview.md
docs/docs/platform/entities/overview.md
docs/docs/platform/objects/overview.md
docs/docs/tutorials/build-field-mapping-ui.md

docs: some cleanup around Entities

---

packages/core/destination_writers/postgres.ts

fix: don't enforce PK constraint in temp table

---

packages/core/lib/entity.ts
packages/core/services/connection_service.ts
packages/core/services/entity_service.ts
packages/core/services/provider_service.ts

chore: validate schema and entity field names to avoid collisions

---

packages/core/remotes/impl/salesforce/index.ts

fix: use version 57.0 for jsforce API to fix user column issue

---

packages/core/remotes/impl/salesforce/index.ts

chore: use same API version everywhere for salesforce

---

apps/api/middleware/private_whitelist.ts
apps/api/routes/index.ts
apps/api/routes/private/index.ts
apps/api/routes/private/v2/customer/connection/index.ts
apps/api/routes/private/v2/customer/index.ts
apps/api/routes/private/v2/index.ts
packages/core/services/connection_service.ts

chore: connection api for customer

---

packages/db/prisma/migrations/20230810221512_syncrun_index/migration.sql
packages/db/prisma/schema.prisma

chore: add index on order by key

---

packages/db/prisma/migrations/20230810221609_encrypted_destination_config/migration.sql
packages/db/prisma/schema.prisma

chore: add DB field for encrypted destination config

---

apps/mgmt-ui/src/components/logs/SyncRunsTable.tsx
apps/mgmt-ui/src/components/logs/SyncsTable.tsx
apps/mgmt-ui/src/hooks/useSyncRuns.ts
apps/mgmt-ui/src/hooks/useSyncs.ts
apps/mgmt-ui/src/pages/api/internal/sync-runs/index.ts
apps/mgmt-ui/src/pages/api/internal/syncs/index.ts
apps/mgmt-ui/src/pages/applications/[applicationId]/sync_runs/index.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/syncs/index.tsx
apps/mgmt-ui/src/utils/filter.ts
apps/mgmt-ui/src/utils/snakecase.ts

Fixes: SUP2-548
Tested locally
https://www.loom.com/share/fa776a0e8d7043f48b3ddaf00c16c443

feat: ability to filter syncs and sync runs

---

apps/api/routes/internal/system/index.ts
packages/core/mappers/destination.ts
packages/core/services/destination_service.ts

- encrypt destination creds on create and update
- read creds for encrypted creds if available
- include endpoint to backfill all creds with encrypted creds
next steps:
- prepare PR to remove non-encrypted creds

chore: encrypt destination creds on create/update

---

apps/api/middleware/private_whitelist.ts

fix: add dev env too

---

apps/api/routes/internal/system/index.ts
packages/core/mappers/destination.ts
packages/core/services/destination_service.ts
packages/db/prisma/migrations/20230811201204_drop_destination_config/migration.sql
packages/db/prisma/schema.prisma

I already ran the backfill in staging and production.

chore: deprecate destination config in favor of encrypted

---

apps/api/routes/mgmt/v2/customer/connection/index.ts
packages/core/services/application_service.ts
packages/core/services/connection_service.ts
packages/core/services/customer_service.ts
packages/core/services/entity_service.ts
packages/core/services/schema_service.ts

chore: stable order for all list endpoints

---

packages/db/prisma/migrations/20230811202749_application_notes/migration.sql
packages/db/prisma/schema.prisma

This is to make debugging easier (i.e. add org names, other notes) in prod

chore: add notes field to application

---

packages/core/destination_writers/postgres.ts
packages/sync-workflows/activities/maybe_send_sync_finish_webhook.ts

Fixes some issues I noticed while doing the dogfooding

fix: schemas with special characters in their names, webhook shape

---

docs/docs/platform/notification-webhooks.md
docs/docs/tutorials/listen-for-webhooks.md

docs: more webhooks

---

docs/docs/platform/notification-webhooks.md
docs/docs/tutorials/listen-for-webhooks.md

docs: webhook docs touchup

---

apps/mgmt-ui/src/pages/applications/[applicationId]/customers/[customerId]/connections/[providerName]/index.tsx

Fixes the issue reported by @george-xing [here](https://supaglue.slack.com/archives/C01GBBSL0JU/p1692059288573939)
Tested locally

fix: handle errors from metadata endpoints gracefully

---

docs/docs/api/v2/actions/sidebar.js
docs/sidebars.js
docs/src/css/supaglue.css
yarn.lock

docs: re-organize actions API hierarchy

---

packages/core/destination_writers/postgres.ts

fix: escape all table names

---

packages/core/remotes/impl/hubspot/mappers.ts

fix: respect undefined hubspot deal stage and pipeline

---

package.json
packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/postgres.ts
packages/utils/index.ts
packages/utils/package.json
packages/utils/slugify.ts
scripts/setup_dev_env.sh
yarn.lock

I checked prod and this shouldn't cause any issues with any current tables.

fix: normalize table names

---

packages/core/destination_writers/postgres.ts
packages/db/prisma/migrations/20230821174715_index/migration.sql
packages/db/prisma/schema.prisma
packages/sync-workflows/services/sync_service.ts

Also adding some logs to see if there is prisma latency/timeout issue.

fix: don't run sync reconciler in transaction

---

apps/mgmt-ui/next.config.js
packages/core/jest.config.js

Prevents @asdfryan's issue with sentry-cli on test runs

chore: don't send sentry sourcemaps on local

---

docs/docs/tutorials/transformations/date-time-conversion.md
docs/docs/tutorials/transformations/overview.md
docs/docs/tutorials/transformations/value-mapping.md
docs/sidebars.js

docs: remove two tutorials

---

packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/postgres.ts
packages/core/keys/engagement/contact.ts
packages/core/mappers/engagement/contact.ts
packages/core/remotes/impl/apollo/mapper.ts
packages/core/remotes/impl/outreach/mappers.ts
packages/core/remotes/impl/salesloft/mappers.ts
packages/core/services/destination_service.ts
packages/types/engagement/contact.ts

feat: support contact -> account associations in engagement vertical

---

packages/core/destination_writers/postgres.ts

Removing this because if this part fails, it'll fail the whole sync. Better to just run the migration manually.

fix: remove account_id migration

---

apps/mgmt-ui/src/components/connectors/provider/ProviderDetailsPanel.tsx

fix: FE not building for oauth provider config

---

apps/api/routes/enrichment/index.ts
apps/api/routes/oauth.ts
apps/api/services/connection_and_sync_service.ts
apps/api/services/magic_link_service.ts
apps/mgmt-ui/src/components/connectors/provider/ProviderDetailsPanel.tsx
apps/mgmt-ui/src/pages/links/[linkId].tsx
packages/types/connection.ts

feat: connect clearbit successfully end-to-end from FE

---

docs/sidebars.js

docs: hide entities, schemas

---

packages/db/prisma/migrations/20230831175859_connection_sync_config/migration.sql
packages/db/prisma/schema.prisma

chore: connectionSyncConfig on DB model

---

packages/core/destination_writers/mongodb.ts
packages/core/destination_writers/postgres.ts
packages/core/errors.ts

chore: add error specific to cache invalidation

---

packages/core/remotes/impl/hubspot/index.ts

Instead of 
```
{
...
"properties": {
...
},
"associations": {
"contacts": [
"101"
],
"2-17410842": [
"7999197075",
"7999197075"
]
}
}
```
do this
```
{
...
"properties": {
...
},
"associations": {
"contact": [
"101"
],
"2-17410842": [
"7999197075",
"7999197075"
]
}
}
```

chore: make hubspot association keys singular instead of plural

---

apps/mgmt-ui/src/components/connectors/provider/ProviderDetailsPanel.tsx

fix: provider config oauth

---

packages/db/prisma/migrations/20230905231438_destination_version/migration.sql
packages/db/prisma/schema.prisma

record destination version for connection pool cache invalidation later

chore: destination version db model

---

apps/mgmt-ui/Dockerfile

chore: fix broken build script for mgmt-ui

---

packages/core/remotes/impl/outreach/index.ts

fix: use newly-refreshed access token for outreach on syncs

---

apps/api/routes/mgmt/v2/index.ts

fix: mgmt provider path

---

packages/core/remotes/categories/marketing_automation/base.ts
packages/core/remotes/categories/marketing_automation/index.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/marketo/index.ts
packages/core/remotes/impl/salesforce_marketing_cloud_account_engagement/index.ts
packages/core/services/common_objects/marketing_automation/common_object_service.ts
packages/core/services/remote_service.ts
packages/types/marketing_automation/index.ts
packages/types/marketing_automation/submit_form.ts

feat: hubspot form apis

---

apps/api/mappers/hubspot.ts

fix: return raw hubspot response for data listing

---

apps/mgmt-ui/src/components/connectors/destination/DestinationTabPanelContainer.tsx
apps/mgmt-ui/src/components/connectors/provider/ProviderDetailsPanel.tsx
apps/mgmt-ui/src/components/connectors/provider/ProviderTabPanelContainer.tsx
apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigListPanel.tsx
apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigTabPanelContainer.tsx
apps/mgmt-ui/src/layout/Navigator.tsx
apps/mgmt-ui/src/pages/_app.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/connectors/[...tab].tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/syncs/[...tab].tsx

- guard schemas and entities except for select customers
- remove s3 as a destination in ui

chore: some cleanup for schemas, entities, s3

---

packages/core/remotes/impl/outreach/mappers.ts

fix: outreach should map jobTitle -> title for contact

---

packages/core/remotes/impl/intercom/index.ts

fix: intercom pagination

---

packages/core/remotes/impl/intercom/index.ts

- this uses undocumented GET endpoint for listing companies

fix: list intercom companies

---

packages/sync-workflows/services/sync_service.ts

Setting this as WIP, because I can't find an easy way to backfill search attributes on Temporal schedules yet.
https://temporalio.slack.com/archives/CTRCR8RBP/p1694460216326639

chore: set temporal search attributes on schedules

---

docs/docs/providers/intercom.md
packages/core/remotes/impl/intercom/index.ts

- implement documented `GET /companies/scroll` sync
- bring back other endpoints

chore: restore intercom functionality

---

packages/core/destination_writers/bigquery.ts

fix: bigquery standard object syncs

---

packages/core/remotes/impl/intercom/index.ts

fix: intercom _supaglue_last_modified_at

---

packages/core/remotes/impl/salesforce/index.ts

fix: salesforce inferred title

---

docs/docs/providers/intercom.md
docs/sidebars.js

docs: intercom managed syncs

---

packages/core/remotes/impl/hubspot/index.ts
packages/core/services/common_objects/crm/common_object_service.ts

fix: only fetch necessary properties when cache invalidating

---

packages/core/destination_writers/bigquery.ts

fix: bigquery sync for eng contact

---

apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx

feat: expose sync strategy in mgmt ui

---

packages/core/remotes/impl/outreach/index.ts

feat: return outreach prospect properties

---

packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/hubspot/mappers.test.ts
packages/core/remotes/impl/hubspot/mappers.ts

Reverts supaglue-labs/supaglue#1586

chore: revert "feat: fetch all associations for common object syncs and gets"

---

packages/core/destination_writers/postgres.ts

fix: fix syntax

---

packages/core/destination_writers/postgres.ts

chore: perf improvement by filtering destination first before NOT EXISTS

---

apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx
docs/docs/providers/apollo.md
docs/docs/providers/gong.md
docs/docs/providers/hubspot.md
docs/docs/providers/intercom.md
docs/docs/providers/linear.mdx
docs/docs/providers/ms_dynamics_365_sales.md
docs/docs/providers/outreach.md
docs/docs/providers/pipedrive.md
docs/docs/providers/salesforce.mdx
docs/docs/providers/salesloft.md

docs: more soft delete and incremental clarity. apollo limitations

---

packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/hubspot/mappers.test.ts
packages/core/remotes/impl/hubspot/mappers.ts

Reverts supaglue-labs/supaglue#1600

feat: fetch all associations for common object syncs and gets

---

packages/core/destination_writers/bigquery.ts
packages/core/destination_writers/mongodb.ts
packages/core/destination_writers/postgres.ts
packages/core/lib/constants.ts

chore!: don't write mapped_data for users unless whitelisted

---

docs/docs/integration-patterns/managed-syncs.mdx
docs/docs/platform/common-schemas/overview.mdx
docs/docs/platform/objects/overview.mdx
docs/docs/platform/overview.md
docs/sidebars.js

docs: add data models (common schema and objects)

---

apps/api/routes/internal/_multitenant_backfill/index.ts

- decrease take from 5000 to 2000
- increase timeout from 10s to 15s

chore: increase backfill timeout and add more logging

---

.github/workflows/docker_build_and_push.yml

chore: try github larger runners for actions

---

.github/workflows/ci.yml

chore: try larger runner part 2

---

apps/api/routes/internal/_multitenant_backfill/index.ts
apps/mgmt-ui/src/components/logs/SyncRunsTable.tsx
packages/core/services/sync_run_service.ts
packages/db/prisma/migrations/20230920061932_object_sync_run_pk_change/migration.sql
packages/db/prisma/migrations/20230920062058_object_sync_run_drop_old_id/migration.sql
packages/db/prisma/migrations/20230920063020_object_sync_run_rename_cuid/migration.sql
packages/db/prisma/migrations/20230920064701_object_sync_run_rename_cuid_to_id/migration.sql
packages/db/prisma/schema.prisma
packages/sync-workflows/activities/log_sync_start.ts
packages/sync-workflows/workflows/run_object_sync.ts

fix!: change sync run id pk, drop id col
fix!: change sync run id pk

feat!: (step 2/2) rename object_sync_runs cuid to id

---

packages/core/remotes/impl/salesforce/index.ts
packages/core/remotes/impl/salesforce/mappers.test.ts
packages/core/remotes/impl/salesforce/mappers.ts

Tested locally with dev salesforce instance

fix: remove usage of metadata api for getting and listing custom salesforce objects

---

apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigListPanel.tsx

fix: make it more obvious how to edit sync config

---

packages/core/remotes/impl/salesforce/index.ts

fix: salesforce upsert

---

.github/workflows/docker_build_and_push.yml

chore: tag builds that land on main using short sha

---

apps/api/routes/crm/v2/account.ts
apps/api/routes/crm/v2/contact.ts
apps/api/routes/crm/v2/lead.ts

We need to fix this because there's 1 more additional layer of nesting.

fix: camelcasing for upsert

---

packages/core/remotes/categories/crm/base.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/salesforce/index.ts
packages/core/services/common_objects/crm/common_object_service.ts
packages/types/field_mapping_config.ts

fix: use fieldmappings for common object fetches

---

apps/api/lib/posthog.ts
openapi/v2/engagement/openapi.bundle.json
packages/schemas/gen/v2/engagement.ts

Fixes: SUP-657
Also includes some changes from `yarn generate`

fix: logging provider name to posthog

---

apps/api/lib/posthog.ts

fix: add customer id to posthog events

---

apps/api/lib/posthog.ts
packages/sync-workflows/activities/log_sync_finish.ts
packages/sync-workflows/activities/sync_entity_records.ts
packages/sync-workflows/activities/sync_object_records.ts
packages/sync-workflows/lib/analytics.ts

fix: add application id to posthog events

---

apps/api/routes/actions/index.ts
apps/api/routes/actions/v2/index.ts
apps/api/routes/crm/index.ts
apps/api/routes/crm/v2/index.ts
apps/api/routes/data/index.ts
apps/api/routes/data/v2/index.ts
apps/api/routes/engagement/index.ts
apps/api/routes/engagement/v2/index.ts
apps/api/routes/enrichment/v2/index.ts
apps/api/routes/marketing-automation/index.ts
apps/api/routes/marketing-automation/v2/index.ts

fix: log pino context needs to come after open api middleware

---

apps/api/routes/actions/v2/index.ts

chore: add more context for passthrough

---

packages/core/remotes/impl/pipedrive/index.ts

fix: pipedrive incremental date comparison

---

packages/core/remotes/impl/pipedrive/index.ts
scripts/build_and_push.sh

- pipedrive incremental fix 1 only fixed it for the first page
- this fixes it for subsequently paginated records
- revise build_and_push script to allow for tagging of images for hotfixes

fix: pipedrive incremental fix 2 and build_and_push script update for hotfixes

---

apps/api/routes/internal/api_key/index.ts
apps/mgmt-ui/src/client.ts
apps/mgmt-ui/src/components/settings/ApiKeyTabPanel.tsx
apps/mgmt-ui/src/pages/api/internal/api_keys/create_temporary.ts
packages/core/services/application_service.ts
packages/db/prisma/migrations/20231010212440_temporary_api_key/migration.sql
packages/db/prisma/schema.prisma

feat: temporary API Key

---

.gitignore
packages/core/destination_writers/bigquery.ts

Address forgotten case in https://github.com/supaglue-labs/supaglue/pull/1720

fix: Add missing table setup queries for bigquery unified data jsonb column

---

apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigListPanel.tsx
packages/core/remotes/impl/hubspot/index.ts
packages/sync-workflows/services/sync_service.ts

fix: hubspot association dedup + custom object sync start

---

Dockerfile.dev
apps/api/index.ts
depot.json
docker-compose.yml

This restores the ability to use `docker compose watch` for local development

chore: restore docker compose watch functionality

---

packages/core/remotes/impl/apollo/client.ts

fix: staging build due to json import

---

apps/mgmt-ui/src/components/syncs/syncConfig/SyncConfigDetailsPanel.tsx
apps/mgmt-ui/src/layout/Navigator.tsx
apps/mgmt-ui/src/pages/applications/[applicationId]/settings/[...tab].tsx

- Change sync config label for common objects to be "Supaglue common objects" for clarity and to disambiguate with standard/custom objects
- Switch tab order of API key and Webhooks since API key is most frequently used and Webhooks has a few-second delay

chore: minor UX improvements from onboarding

---

docs/docs/integration-patterns/unified-api.mdx
docs/docs/platform/common-schemas/crm.md
docs/docs/platform/common-schemas/engagement.md

docs: flesh out crm and engagement common schemas

---

packages/core/remotes/impl/hubspot/mappers.ts
packages/core/remotes/impl/salesforce/mappers.ts

We were also losing precision (parseInt instead of parseFloat)

fix: introduce upper limit for amount (hubspot only)

---

packages/core/services/customer_service.ts

fix: disallow creating customer with empty id

---

docs/docs/platform/common-schemas/engagement.md

feat: Update docs for engagement api improvements

---

packages/core/mappers/application.ts
packages/types/application.ts

fix: notification service

---

packages/core/remotes/impl/salesforce/index.ts

chore: add inactive sfdc user to autopause list

---

apps/mgmt-ui/src/pages/applications/[applicationId]/index.tsx

chore: disable lekko for now for page load perf

---

scripts/generate_sync_runs.ts

chore: script to generate sync runs

---

docs/docs/tutorials/transformations/pagination.mdx

docs: update pagination tutorial to include listing api

---

apps/api/services/connection_and_sync_service.ts

- Tested auth then reauthing and observing the instance url be updated

fix: update connection instance url upon reauth

---

.github/workflows/api_build_docker.yml
.github/workflows/integration_tests.yml
.github/workflows/production_integration_tests.yml
apps/api/integration-test-environment.js
apps/api/routes/mgmt/v2/customer/connection/connection.integration.test.ts
apps/api/routes/mgmt/v2/customer/connection/index.ts
apps/api/services/connection_and_sync_service.ts
packages/core/services/application_service.ts
packages/core/services/connection_service.ts
packages/core/services/customer_service.ts

- Tested negative and positive cases for LIST, GET, _provider_user_id

fix: respect customer id in path for connection apis. peg integration tests to release tag for prod

---

.github/workflows/production_integration_tests.yml

fix: try production integration test fix

---

packages/core/remotes/impl/hubspot/index.ts

We should not assume the category is `USER_DEFINED`. Instead, do a fetch and check what category it is.
Tested locally

fix: hubspot associations should not assume USER_DEFINED category

---

apps/api/routes/crm/v2/metadata/custom_objects/custom_objects.integration.test.ts

fix: custom objects integration test

---

packages/core/services/destination_service.ts

fix: remove statement timeout from test conection

---

packages/core/destination_writers/postgres_impl.ts

fix: skip last modified at timestamps that are the same

---

apps/mgmt-ui/src/components/connectors/provider/ProviderCard.tsx

fix(mgmt-ui): change language on providers list from connected to configured

---

packages/core/destination_writers/postgres_impl.ts

- Revert pipe perf changes for now
- Need to investigate more for a 2-pass approach or other optimizations

fix: revert pipeline perf changes

---

packages/core/destination_writers/postgres_impl.ts

fix: order by syntax

---

packages/core/remotes/impl/hubspot/index.ts

feat: support opportunity lists

---

packages/core/destination_writers/postgres_impl.ts

fix: abstract supaglue id in query

---

scripts/prepare_release.sh
scripts/release.sh

This makes the `--skip_tests` optional

fix: release script

---

packages/core/remotes/impl/apollo/index.ts
packages/core/remotes/impl/outreach/index.ts

fix: autopause for apollo + outreach

---

apps/api/routes/engagement/v2/contact.integration.test.ts

I see this error: `The maximum number of api calls allowed for api/v1/contacts/search is 2000 times per day. Please upgrade your plan from https://app.apollo.io/#/settings/plans/upgrade`

chore: skip search for apollo in integration tests

---

packages/core/remotes/impl/ms_dynamics_365_sales/index.ts

feat: implement uncached reads for Microsoft

---

packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/core/remotes/impl/pipedrive/index.ts

feat: uncached reads for pipedrive and dynamics

---

packages/core/lib/constants.ts
packages/core/remotes/impl/hubspot/index.ts

429 for axios hubspot client
- add axios retry for some places that was missing it
- turn on retries for hubspot client

fix: retry on 429 or 5xx failures for native hubspot client. retry on

---

apps/api/routes/mgmt/v2/customer/connection/connection.integration.test.ts

fix: connection integration tests

---

apps/api/routes/crm/v2/metadata/properties/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/mappers.ts

feat: support dynamics in crm list properties endpoint

---

packages/core/remotes/impl/pipedrive/index.ts
packages/core/remotes/impl/pipedrive/mappers.ts
packages/core/remotes/impl/pipedrive/types.ts

feat: list properties endpoint for pipedrive

---

apps/mgmt-ui/package.json
apps/mgmt-ui/src/pages/_app.tsx
packages/core/mappers/application.ts
packages/db/prisma/migrations/20231121215407_app_is_paid/migration.sql
packages/db/prisma/schema.prisma
packages/types/application.ts
yarn.lock

- `is_paid` flag on application data model. true = shows. false = hidden.
- (unfortunate we don't have a org data model so we'll have to do this per application.)
- modify `createdAtDate` on application to adjust the days remaining

feat: trial banner

---

packages/core/remotes/impl/salesloft/index.ts

This was removed in #1938 for some reason

fix: restore salesloft retry config

---

packages/core/package.json

chore: Fix tsx issue running on some dev machines

---

packages/core/lib/pagination.test.ts
packages/core/lib/pagination.ts

feat!: URL-encode cursors

---

apps/mgmt-ui/src/components/Banner/index.tsx
apps/mgmt-ui/src/layout/Header.tsx
apps/mgmt-ui/src/pages/_app.tsx

- move banner to app area only to fix scroll behavior between navigator and app

fix: slightly better banner scroll behavior

---

docs/docs/platform/common-schemas/crm.md
docs/docs/platform/common-schemas/engagement.md

docs: fix common schema docs

---

openapi/v2/engagement/openapi.yaml
openapi/v2/engagement/paths/accounts@search.yaml

docs: improve search engagement accounts API docs and organization

---

packages/core/remotes/impl/salesforce/index.ts

- fix logic for `fromClause`
- keep pagination and others the same
- tested different account lists locally
- tested contact locally

fix: dynamic and static list membership for sfdc

---

packages/sync-workflows/activities/sync_entity_records.ts
packages/sync-workflows/activities/sync_object_records.ts

No longer required as we already heartbeat on a 10 second interval while syncs are running.

chore: remove unnessessary heartbeating readable code

---

packages/core/remotes/categories/crm/base.ts
packages/core/remotes/impl/hubspot/index.ts
packages/core/remotes/impl/ms_dynamics_365_sales/index.ts
packages/core/remotes/impl/pipedrive/index.ts
packages/core/remotes/impl/salesforce/index.ts
packages/core/services/common_objects/crm/common_object_service.ts
packages/core/services/connection_service.ts
packages/types/field_mapping_config.ts

Reverts supaglue-labs/supaglue#2055

chore: revert "chore: inject all CRM field mappings into CRM clients (for expand to work)"

---

packages/core/remotes/utils/paginator.ts

This reverts commit e81f6368621ea0e107ae7f0c4bf63e1183ceba55.

fix: Revert "fix: stream error handling (#2054)"
